### ISSUE TITLE
Save content on back/return button press

### ISSUE THREAD

**Issue by AlexanderRavenheart** [SimpleMobileTools/Simple-Notes#10]
Auto save or ask to save if the user presses the back/return key so that they do not lose content.
Most apps on Android autosave or ask to save for edited content so I believe this is expected behaviour.

**Comment by tibbi** [comment]
there is already an Autosave function, it can be enabled in the Settings. I didnt want to enable it by default because with it enabled the Save icon isnt visible, which might confuse people.

**Comment by AlexanderRavenheart** [comment]
![screenshot_2016-08-03-10-51-38-202](https://cloud.githubusercontent.com/assets/7274337/17358041/5b5bb68e-5968-11e6-9e77-bac061e0ada6.jpeg)

Which Settings menu?

**Comment by tibbi** [comment]
okay, I will close this issue then. The autosave feature might change in the future, like be enabled by default or so. I could at least prompt the user at leaving if he has unsaved changes.
