### ISSUE TITLE
Allow using the app as the default file opener

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#107]

**Comment by trubitsyn** [comment]
@tibbi hello. May I take this request to implement?

**Comment by tibbi** [comment]
sure, just go ahead

**Comment by trubitsyn** [comment]
@tibbi I have implemented that, but one thing makes it not ready yet. Should it save opened file automatically? I made it do so, but now if I open the same file multiple times, it complains a note with that title already exists. Appending symbols to the  file name won't fix this. I think that notes should be identified by their IDs and that it should be allowed to have multiple notes with equal titles.

Or we shouldn't save that file automatically at all.

**Comment by tibbi** [comment]
I definitely dont want to allow multiple notes with the same title, that would be a superconfusing madness. We can save the file as a note automatically and store it in the db. Then the next time you open the same note you check the "path" column in the database. If some note already has the given path, just go to the selected note. Since the "path" field is filled, the note is synced automatically with the given file, so there shouldnt be any conflicts with different file content or so.

**Comment by tibbi** [comment]
if a note with the given filename already exists, just append something after it, like "(file)" or so. Its an edge case, wont happen often anyway.

**Comment by trubitsyn** [comment]
Thanks for guiding me, could you just clarify this one:

> Since the "path" field is filled, the note is synced automatically with the given file

So syncing with file should be enabled by default? As of now it uses a dialog prompting whether to just import or import and sync.

**Comment by tibbi** [comment]
yea, enable syncing with the opened file immediately. That means that the note wont have any text stored in the database, just the path.

**Comment by trubitsyn** [comment]
@tibbi Here it is: #113. I'm sorry for a delay.

**Comment by tibbi** [comment]
okay, thanks. I wrote a couple notes, some things are complicated unnecessarily.

**Comment by trubitsyn** [comment]
@tibbi this can be closed
