### ISSUE TITLE
Allow selecting monospace (instead of sans) font for text entry field

### ISSUE THREAD

**Issue by carlosdavidepto** [SimpleMobileTools/Simple-Notes#110]
Being able to switch the text on the notes to monospace would allow notes taken on other monospaced text editors (vim, emacs, nano, etc.) to retain their spatial layout.

This is very useful for more complex notes, such as those written in markdown or bullet journals.

Given that the settings already provide the ability to select font size, this shouldn't be a compromise of the app's simplicity (which is in my opinion is it's best feature).

**Comment by trubitsyn** [comment]
Should the text be changed for all notes or for each note separately?

**Comment by tibbi** [comment]
all notes for sure, dont complicate it
