### ISSUE TITLE
option to not show the keyboard automaticly 

### ISSUE THREAD

**Issue by redojg** [SimpleMobileTools/Simple-Notes#111]

**Comment by redojg** [comment]
would be nice to also not show keyboard when switching apps

**Comment by tibbi** [comment]
right, i see

**Comment by redojg** [comment]
seems like it actually works like this, just requires a restart after toggling an option

**Comment by redojg** [comment]
Cant reproduce, sometimes it remembers if the keyboard was opened, sometimes it does not.

**Comment by tibbi** [comment]
thats good enough, i dont want to mess more with the keyboard
