### ISSUE TITLE
[Bug] The note widget belongs to not shown on widget click if app is in background

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#120]
I think it would be more user-friendly to open a note on widget click, especially when note text does not fit into the widget's view.

Currently clicking on widget just reopens the app. You can open settings or any of the dialogs, hide the app, click on the widget and... See the same settings view/dialog! Confusion.

**Comment by trubitsyn** [comment]
@tibbi it actually works as expected, but only on first launch.

**Comment by tibbi** [comment]
ye it depends if you quit the app with the Back button, or just pause with Home

**Comment by Maxime-J** [comment]
It joins what I recently sent you by mail @tibbi.
the behavior is weird, it does work sometimes, but not on first launch and more often, it doesn't.
Worse, you can have to press back multiple times to exit the app after a specific scenario \:

_From the app not in memory, with a widget on home screen_
Open with the launcher icon and press Home
Click on the widget and press Home (X times)
Re-click on the widget or use the launcher icon
From that point, you would have to press back multiple times to exit, depending of how many times the widget has been clicked.
