### ISSUE TITLE
Note type is unused

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#125]
https://github.com/SimpleMobileTools/Simple-Notes/blob/02334c8327e80b23c45967abd959dafbf30832d7/app/src/main/kotlin/com/simplemobiletools/notes/helpers/DBHelper.kt#L66

Should I create a PR to save `note.type` in DB? Or might it be possible to get rid of note types completely for now? #28 is not implemented yet anyway, why keep useless code.

If someone wants to implement #28, he/she will be able to revert the changes and build on top of that code or even find a better solution if any.

**Comment by tibbi** [comment]
its ok, just keep it for now
