### ISSUE TITLE
Scrolling note in widget

### ISSUE THREAD

**Issue by nazar-pc** [SimpleMobileTools/Simple-Notes#127]
Could you make widget contents scrollable vertically for long notes? I have this feature in another similar app and it is very useful.

**Comment by tibbi** [comment]
I wanted to do it already, but as far as I can tell only list-like widgets can be vertically scrollable, a simple textview like this cannot. Can you tell me the app which has a vertically scrollable widget, so I could check it out? Thanks

**Comment by nazar-pc** [comment]
Here is an app I'm currently using: https://github.com/SimonMcDonnell/Noted
But it is not on F-Droid, so I'm looking for replacement.

**Comment by tibbi** [comment]
ok thanks, I will take a look at it later

**Comment by tibbi** [comment]
so this was quite a lot more difficult than I wanted, but it seems to be working. Thanks

**Comment by nazar-pc** [comment]
Will new version be published to F-Droid soon?

**Comment by tibbi** [comment]
Im not sure, f-droid seems to suck lately. It hasnt updated quite a few of my apps. I will take a look at it tomorrow.

**Comment by tibbi** [comment]
seems like it is an f-droid issue, their build process gets messed up from time to time. More info at https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195
