### ISSUE TITLE
disable autosave option

### ISSUE THREAD

**Issue by protoloo** [SimpleMobileTools/Simple-Notes#133]
Please, disable the autosave or let the user decide when to use it

**Comment by smichel17** [comment]
What's a use case where you don't want your notes to autosave?

**Comment by protoloo** [comment]
Simply because I happened to delete words or entire links by mistake and obviously I did not have the opportunity to retrieve them.

**Comment by smichel17** [comment]
@protoloo Would a history or undo function fit that use case as well as autosave?

**Comment by tibbi** [comment]
I will probably add both. An option for autosave (enabled by default) and an Undo button.

**Comment by trubitsyn** [comment]
You will have to add a save button then when autosave is disabled, I guess. I kindly ask you to place it in the toolbar before the folder icon (the dropdown menu is cluttered already) and make it visible only if a note change has been made. Thanks.

**Comment by smichel17** [comment]
Wherever the save button is, should be the same spot as the undo button if autosave is enabled.
