### ISSUE TITLE
Add an extension field to "Export as file"

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#135]
And make it txt by default

**Comment by trubitsyn** [comment]
In my case notes are stored in files with no extension at all, so it would be great if there was a way to disable such field (maybe deep in the settings).

**Comment by tibbi** [comment]
if you clear the extension field it wont add any. I dont think having a .txt extension in your case would cause any issues anyway, would it?

**Comment by trubitsyn** [comment]
I realize this is an edge case, but I just don't like to name it .txt without any purpose, it's hard to read (for me) non-English filenames with `.txt` and Android opens no-extension files as plain text perfectly. As I usually save a lot of notes at once, clearing the extension field every time would be a waste of time.

**Comment by tibbi** [comment]
well the default extension will be the last used extension, so it should be ok for you. I dont want to add any checkboxes for it.

**Comment by trubitsyn** [comment]
Nice, thank you.
