### ISSUE TITLE
SwiftKey arrows not working properly

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#136]
The user also uses TouchType, not sure if it is related

**Comment by tibbi** [comment]
also check the arrows at the navigation bar at GNotes on Android 7. Android 8 built in navigation arrows work fine.

**Comment by genodeftest** [comment]
Same here with AnySoft Keyboard's upper row arrow keys.

**Comment by tibbi** [comment]
will be fixed in 3.2.0
