### ISSUE TITLE
Widget is stuck loading forever

### ISSUE THREAD

**Issue by Zero3** [SimpleMobileTools/Simple-Notes#167]
Hiya

Ever since the recent update (3.1.1), my notes widget has been stuck saying "Loading...". It has been like that for weeks now.

Clicking it (outside the loading text) works fine, and opens the note as usual.

Running Android 8.1 on a Google Nexus 6P.

**Comment by tibbi** [comment]
Must have been some glitch, i dont think it will appear again. Try recreating the widget if it is still stuck.
