### ISSUE TITLE
Character size

### ISSUE THREAD

**Issue by ayac** [SimpleMobileTools/Simple-Notes#17]
It would be good to have the possibility to set the size of characters (i need bigger chars than the default :-).
Thanks.

**Comment by tibbi** [comment]
Ive added a setting for changing font size, let me know if the Large font isnt large enough.

**Comment by ayac** [comment]
It's fine, however i think having an XLarge font size option also would be convenient.
Thanks for fixing this issue.

**Comment by tibbi** [comment]
will do :)
