### ISSUE TITLE
Changing the color of the icon

### ISSUE THREAD

**Issue by nicd23** [SimpleMobileTools/Simple-Notes#176]
First I want to say thanks for creating this amazing app, and others (I also use the Gallery, Flashlight and File Manager). It would awesome to add option to change color of this and other apps icons from Simple Mobile Tools group. There is too much orange color in the launcher when multiple Simple apps are installed.

**Comment by tibbi** [comment]
I moved the report at https://github.com/SimpleMobileTools/General-Discussion/issues/54 , as it affects all apps. Anyway, I wanted to do it already, but I would have to upload many new versions of the launcher icon and that would increase the app size a lot. I might find some better way in the future.
