### ISSUE TITLE
Auto save by default

### ISSUE THREAD

**Issue by alexgleason** [SimpleMobileTools/Simple-Notes#18]
I just lost an important note because I didn't know you have to press save.

**Comment by tibbi** [comment]
Sorry for that, it is one of the things I was thinking of quite a lot. Ill enable autosave by default and test how to announce the save. If nothing happens after closing the app, people might not realise that it saved itself. I will test displaying a toast everytime the note gets saved, if its not too annoying.

**Comment by alexgleason** [comment]
Thank you!

You could include a subtle timestamp somewhere on the screen, preferably in a fixed location, that says "*Last saved: 1/1/16, 12:00 PM*". Perhaps you can let the user force a save by pulling the note down (similar to refreshing a webpage).

My problem was that I switched out of an open note (into another app), shut off my screen for a bit, and the note got picked up by garbage collection for sitting closed in my recent apps for too long. When I switched back it was blank.

Thanks for your work on this.

**Comment by tibbi** [comment]
the save will be happening in the onPause event, which triggers everytime you leave that screen. That includes going into the Settings, closing the app, pressing Home, or even locking the screen. Should be good enough ;)
