### ISSUE TITLE
[Feature request] Online sync

### ISSUE THREAD

**Issue by matiasblomqvist** [SimpleMobileTools/Simple-Notes#180]
I would like no-registration type online sync. User goes Settings > Online sync. A popup appears on app saying "Your ID is a8kgjs6534s Go to http://notes.simplemobiletools.com/ to read and edit notes online." This ID is ofc randomly generated, used client-side to encrypt all the notes. Encrypted notes are then sent to server and stores. User opens the URL on desktop browser, enters the ID in a text field and clicks "Login". Decryption can againt be done client-side. List of notes is shown, then you can click to open and edit in a text field.

I thought about making this kind of app myself but life got in the way of Android developing. Plausible?

**Comment by tibbi** [comment]
I dont plan making the apps online, nor creating server side, so no, but thanks.
