### ISSUE TITLE
[Bug]: plus sign disappears after saving

### ISSUE THREAD

**Issue by conrad-heimbold** [SimpleMobileTools/Simple-Notes#182]
How to reproduce: 
1. Type some text with "+"
2. Save document. 
3. Open document again. 

Result: "+" disappears, got replaced by whitespace. 

Expected behaviour: "+" should stay. 

Screenrecord video is below: 
![simplenotes_plus_sign_bug](https://user-images.githubusercontent.com/17474312/37570198-1f1d0b2a-2aed-11e8-8a35-2d5f59d759c3.gif)

**Comment by tibbi** [comment]
that's not even my app...

**Comment by conrad-heimbold** [comment]
Oops, sorry. There are so many note apps. I confused them.
