### ISSUE TITLE
"Black space" in app layout

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-Notes#189]
Is that a bug or feature ? 

Tested on Galaxy S8 with Android 7 

![img_0496](https://user-images.githubusercontent.com/8161283/38151827-274dfa8a-3465-11e8-96f1-c538de00be08.JPG)

**Comment by tibbi** [comment]
that is the Draw app, not Notes. You can select a new color after clicking on it.

**Comment by F3000** [comment]
Ah sorry. I  have choosen the wrong app. When it is possible i would hide this function behind a logo that discribes that :)
