### ISSUE TITLE
New Logo for Simple-Notes

### ISSUE THREAD

**Issue by abdulmalikkhan655** [SimpleMobileTools/Simple-Notes#193]
Hello   , I want contribute to Simple-Note so i designed a new logo for Simple-Notes and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my designed

**Comment by tibbi** [comment]
Hey, Im not looking for a new logo now, thanks.
