### ISSUE TITLE
Where are notes stored?

### ISSUE THREAD

**Issue by jeyca** [SimpleMobileTools/Simple-Notes#229]
I created several notes with the app, now I wanted to include them to my my backup routine and also have a possibility to view them on desktop, but I cannot find the place where they are stored. Is it some hidden database? Or are there files somewhere? I know, there is the option to export the notes to files, but I would have to do this manually.

**Comment by tibbi** [comment]
they are in an internal database. What you need is creating an empty file somehow, then using the "Open file" menu item from Notes. That will synchronize the note and file content automatically. The note content wont actually be stored in any database, it will read/write the actual files.

**Comment by jeyca** [comment]
ok that sounds like a possible workaround, but I will have to do this for each new note, correct?

**Comment by tibbi** [comment]
ye, you will have to. I plan making it a bit easier with enabling synchronization at the "Export as file" item too, we will see when will I get there.
