### ISSUE TITLE
Dark primary colors on dark backgrounds render unreadable links

### ISSUE THREAD

**Issue by DragoonAethis** [SimpleMobileTools/Simple-Notes#231]
Let's say you use the Black & White theme, or use a very dark/black Primary Color in your theme - links and text selection/cursor touch markers are rendered with that color, making them impossible to read on a dark background. The same occurs if you use a Light theme w/ very light primary color, links are white on a white background.

A proposed solution would be something like this:
- Have separate colors for UI and links/markers.
- When the background/primary color is selected, set the link color to the primary color and calculate the WCAG contrast ratio ([here's how](https://www.w3.org/TR/WCAG20-TECHS/G18.html), go to Procedure) to check if it's above a certain threshold (WCAG suggests at least 4.5:1, but that's a bit much - something like 3:1 would probably be enough without randomly breaking still valid themes).
- If below a chosen threshold, take the text color and mix it with the primary color (ratio of 90% text, 10% primay?), then set the link color to that.
- Recalculate the WCAG contrast ratios on the new link color and background, if it's still not good enough then set the link color to the text color.

**Comment by tibbi** [comment]
should be improved in the next version 6.3.1

**Comment by DragoonAethis** [comment]
Thank you! :D
