### ISSUE TITLE
Why note duplicates?

### ISSUE THREAD

**Issue by nlpsuge** [SimpleMobileTools/Simple-Notes#232]
This situation is not very often. Unfortunately It's a little difficult to find out how it happens.

**Comment by tibbi** [comment]
what do you mean? Is the note synced to some file?

**Comment by nlpsuge** [comment]
I think...I'd better using the latest version...

**Comment by tibbi** [comment]
not sure what you mean there. Are you using the latest version, or not? Make sure you use version 5.0.1

**Comment by nlpsuge** [comment]
OK. I'll use version 5.0.1. Thank you.
