### ISSUE TITLE
Add option to search text in the note

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Notes#233]

**Comment by DuMuT6p** [comment]
I also think this would be a very useful feature.

**Comment by herou** [comment]
Do you mind if I develop this feature @tibbi ? What do you think if I add the text "Search" on the three dots menu. Once clicked a material dialog with editext should pop up. If the user input matches with text, the text would be highlighted.

**Comment by tibbi** [comment]
if you want to add it it should work like in the file managers editor. The search icon should be visible at the top menu, then the proper text will be highlighted dynamically without confirming any text.

**Comment by herou** [comment]
Got your idea partly. Could you please be more descriptive what is going to happen after the user clicked the search icon? Thank you.

**Comment by tibbi** [comment]
well the search bar extends at the top menu and the user can type text directly. If it is found in the text, it will be highlighted, there will be no jumping around of the text for now. Just highlighting.

**Comment by tibbi** [comment]
this has already been added in 6.5.0
