### ISSUE TITLE
Renaming a note without inducing a save wipes note

### ISSUE THREAD

**Issue by parnikkapore** [SimpleMobileTools/Simple-Notes#239]
### Reproduction
1. Create a note.
2. Type something in the note.
_Don't switch to anothe note or to another app, or the reproduction will fail as a save is induced._
3. Rename the note to something else.
> The contents of the note is lost to oblivion.
### Expected behavior
The contents of the note is kept.
### Does this happen in pre-paid SN?
Not as far as I can remember.

**Comment by tibbi** [comment]
what app version do you have? Do you have autosave enabled?

**Comment by parnikkapore** [comment]
App version: 6.0.0 (F-droid)
Autosave: Enabled

**Comment by tibbi** [comment]
it has been fixed in 6.0.1 already, the f-droid app should be updated soon
