### ISSUE TITLE
Allow note selection per widget instance

### ISSUE THREAD

**Issue by karcherm** [SimpleMobileTools/Simple-Notes#24]
If you add multiple note widgets, every instance should be able to display its own note. A possible UI for that might be selecting the note on widget creation instead of selecting the note globally in the app.

**Comment by smichel17** [comment]
@tibbi In the meantime, I think widget note selection should be in the settings, not the main menu.

**Comment by tibbi** [comment]
ye that makes sense indeed, ill move it

**Comment by ohthreefive** [comment]
Yup, +1 to this feature request.

Love all the recent developments in the app.

**Comment by tibbi** [comment]
an initial implementation will be added in 4.3.0, let's see how reliable will it be

**Comment by trubitsyn** [comment]
@tibbi, thanks!
