### ISSUE TITLE
FileNotFoundException (Permission Denied)

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [SimpleMobileTools/Simple-Notes#247]
I have a folder with notes that I have imported to a fresh install of SimpleNotes.
I have choosen to keep the changes synced to that folder. 
If I change one note file and switch to another, a toast message with the following text appears:

java.io.filenotfoundexception: /storage/emulated/0/Notes/note.txt: (Permission Denied)

I can edit the file with Amaze text editor without any problem.

**Comment by tibbi** [comment]
what app version and Android OS version do you use?

**Comment by tibbi** [comment]
try with 6.1.0 please, that is the latest one. It isnt on f-droid yet, but it is there on google play, if you use it.

**Comment by java-py-c-cpp-js** [comment]
Sorry, but I only have F-Droid so I will have to wait until it's there...

**Comment by java-py-c-cpp-js** [comment]
Now I have version 6.1.0 and reinstalled the app but still it doesn't work.

**Comment by java-py-c-cpp-js** [comment]
Now it is working. Thank you for solving this error :-)
