### ISSUE TITLE
Allow Export of all Notes to SD-Card

### ISSUE THREAD

**Issue by aunwin** [SimpleMobileTools/Simple-Notes#251]
Using Android 8.0.0 on an HTC U11 Device with Simple-Notes V. 6.1.0 I was not able to *export all notes as files' if I selected a directory on my SD-Card. No error log was shown and no exported files were created.
If this is not a config-setup problem on my behalf, this would be a reasonable feature-request or at least a error-information as bug-fix when selecting SD-Card might be helpful.

Thank you for your work and for considering my suggestion.

**Comment by aunwin** [comment]
Wow, this was a quick one! Just got a Patreon Supporter because I think your excellent work deserves regular support! Thank you very much!

**Comment by tibbi** [comment]
thanks, if I can reproduce some issue, I can probably fix it quite easily too :)
