### ISSUE TITLE
Last checklist item chanhe not saved

### ISSUE THREAD

**Issue by bovergaauw** [SimpleMobileTools/Simple-Notes#258]
The last item (which does not have to be the last item of the list) that's modified in a  checklist does not get saved.

**Comment by tibbi** [comment]
you mean toggling them doesnt get saved, or what? It works fine to me.

**Comment by bovergaauw** [comment]
When I add for instance a new checklist item "k" at the end as a new item, it does not show up

**Comment by tibbi** [comment]
not even after you restart the app? What app version do you have?

**Comment by bovergaauw** [comment]
Found that it does not show up *in the widget* (and I only use widgets). Sorry...
