### ISSUE TITLE
Auto-save checklist irems

### ISSUE THREAD

**Issue by bovergaauw** [SimpleMobileTools/Simple-Notes#260]
When creating a new checklist item and typing outside of the item box, all changes get lost, which in the event of a new itemeand that he entire item gets lost. Typing outside the item box should cause an auto-save IMHO

**Comment by tibbi** [comment]
Not sure what you mean, what typing outside the box?

**Comment by bovergaauw** [comment]
Outside of the text and control box of an item, for instance on the text of another item. Shold have done more testing, but am somewhat unstable while typing at the moment, sorry!

**Comment by tibbi** [comment]
can you maybe explain it with a screenshot? I still dont understand.
