### ISSUE TITLE
regularly save notes as textfiles

### ISSUE THREAD

**Issue by fosBHY** [SimpleMobileTools/Simple-Notes#262]
I want to be able to back up my notes especially since I lost them all once because of phone being stupid in my pocket. For that, I need the notes as a file. I did not find yet where simple-notes stores the data. Export as textfile would be ok. (and Import from it aswell). Even better would be regularly doing so.

**Comment by tibbi** [comment]
well just use the "Export as file" option then. You can then select if the file should be synced with the note too, or make it just a one-time export.
