### ISSUE TITLE
Sorting Checklist-Items by dragging them

### ISSUE THREAD

**Issue by aunwin** [SimpleMobileTools/Simple-Notes#265]
I think an option to sort check-list items manually by dragging them would be an excellent feature improvement on this already great app.

One example for a use case during which I miss that functionality: Say you have a Note 'todos' of Type Checklist, adding items along the way. This feature would allow you to sort your individual todo-items every now and again.
If one had an option to manually move those items, one could:
A) prioritize them
B) move all unchecked items up higher than the already solved items

**Comment by bovergaauw** [comment]
I agree with the author, the requested feature would highly improve the app's usability.

**Comment by tibbi** [comment]
will be added in 6.3.0 released soon

**Comment by aunwin** [comment]
Fabulous! Thank you very much!
