### ISSUE TITLE
[feature request] different widget colours for every note

### ISSUE THREAD

**Issue by Wurzelmann** [SimpleMobileTools/Simple-Notes#269]
I'd love to give each note its own widget colour in order to have a better overview on my launcher's sites, especially when multiple notes are on one page there.

**Comment by domOrielton** [comment]
Might not be a huge help but what I've done is install the Pro and the non-Pro version with different widget setups for both. Unfortunately this only gives you 2 types/colours (I have 1 left justified and 1 center justified) but is is something. I use the left justified one on one page/screen and the center one on another as the center one looks better with the clock.  Hope this helps
