### ISSUE TITLE
Crashes repeatedly when trying to import Downloads

### ISSUE THREAD

**Issue by OrfeasLitos** [SimpleMobileTools/Simple-Notes#273]
After trying to import the Downloads folder (which is rather big and contains a bunch of non-text files, e.g. pdfs, jpgs, m4as) the app crashes every time I try to start it. I even tried to restart, to no avail.

**Comment by tibbi** [comment]
what app version do you have?

**Comment by OrfeasLitos** [comment]
6.1.2, the latest on F-droid. Android 8.1.0

**Comment by tibbi** [comment]
max file size has been reduced from 10 mb to 1 mb in 6.1.4, reopen the issue if you can still reproduce it

**Comment by OrfeasLitos** [comment]
Updated to 6.1.4 (Android 9) and tried again. Unfortunately the same exact problem happens.

**Comment by tibbi** [comment]
many related things changed, reopen if it still happens :)

**Comment by tibbi** [comment]
such apps wont be able to access the Storage permission anymore due to latest Googles permissions policy, so it wont be coming back
