### ISSUE TITLE
Add a checklist type of note

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#28]

**Comment by Jazcafe** [comment]
+1

**Comment by ltGuillaume** [comment]
The most simplistic way I could imagine this being implemented is a menu item to toggle whether 
```- list item 1
- list item 2
x checked item 1
x checked item 2```
is plain text or non-checked items (first two) and checked items (last two).

**Comment by tibbi** [comment]
Im not sure yet how I want to implement it, I would like to avoid long pressing items and the menu

**Comment by ltGuillaume** [comment]
Erm... detect `- ??? ` or `x ??? ` and then add a fixed action button to toggle list mode?

**Comment by tibbi** [comment]
i dont know, I will have to check some other apps when Ill be working on this

**Comment by tibbi** [comment]
an initial implementation will be added in 6.1.0
