### ISSUE TITLE
Large note locks app

### ISSUE THREAD

**Issue by strozek-xx** [SimpleMobileTools/Simple-Notes#280]
My hosts file is too large for Notes to open. Simple-Notes locks when opening the app and the notes can no longer be accessed. Is there a way to remove a note or access the text files without Simple-Notes?

**Comment by strozek-xx** [comment]
Solved bt letting Simple-Notes open in the foreground for a few minutes and pressing Wait. When Simple-Notes is responsive again the note can be removed out of the app.

**Comment by tibbi** [comment]
what app version do you have? The max file size limit has been reduced from 10mb to 1mb in 6.1.4, that should solve it for now.

**Comment by strozek-xx** [comment]
Version 6.1.4 from Fdroid. 
Thanks for the fix.
