### ISSUE TITLE
Number of words is confusing

### ISSUE THREAD

**Issue by herou** [SimpleMobileTools/Simple-Notes#283]
![image](https://user-images.githubusercontent.com/13895430/59599494-f6e7f380-90fe-11e9-81fa-f77e0e372647.png)

I enabled the option count words. At the begin, I did not understand why that number was there.
I think we should write the word "words" next to the number.
For ex: 1 word, 15 words.

**Comment by tibbi** [comment]
the number is not there by default, it appears only if you enable the "Show word count" option in the app settings, which makes it quite clear.
