### ISSUE TITLE
Recommended font size setting to change to numbers instead of text

### ISSUE THREAD

**Issue by xushet** [SimpleMobileTools/Simple-Notes#288]
When I choose huge, I don’t think it’s big enough.I want the font size to be displayed in numbers

**Comment by samikbanik** [comment]
I know this is old, but created a Pull Request to show the font size number along with the text on the dialog with the radio buttons.

**Comment by tibbi** [comment]
What he meant is having a bigger range of sizes, not showing currently predefined sizes in numbers too. That is quite useles like this. Thanks though

**Comment by samikbanik** [comment]
Makes sense. Is it ok if I add more font sizes to the existing predefined sizes ? May be double up the existing range ?

**Comment by tibbi** [comment]
maybe, use some percentages relative to the original default font size at those other ones

**Comment by samikbanik** [comment]
@tibbi I just added some font sizes relative to the default size. Now the question is do we add new texts for these new sizes in addition to Small, Medium, etc, or do we just show each size as just a number as initially raised in the issue ? If texts are to be added, do we have a naming convention ? Localisation updates for all the languages will be required as well. Attaching screenshots for reference.

![Screenshot_20200507-001433_Notes_debug](https://user-images.githubusercontent.com/20096165/81237735-3f9aea80-8ff8-11ea-97ed-e9d951c8d5af.jpg)
![Screenshot_20200507-001257_Notes_debug](https://user-images.githubusercontent.com/20096165/81237736-4164ae00-8ff8-11ea-8e59-ba3cae70e17b.jpg)
![Screenshot_20200507-000055_Notes_debug](https://user-images.githubusercontent.com/20096165/81237739-41fd4480-8ff8-11ea-85b5-06411568f051.jpg)

**Comment by tibbi** [comment]
write it in percentage like 50%, 75%, 100%..., replace the old strings too

**Comment by samikbanik** [comment]
Replaced all the texts with percentages and increased the range of options.

**Comment by tibbi** [comment]
thanks, will take a look at it a bit later
