### ISSUE TITLE
Cannot access notes in app after certain amount of notes has been created

### ISSUE THREAD

**Issue by Neftas** [SimpleMobileTools/Simple-Notes#29]
I use this app to make daily entries. I noticed after using the app a couple of days, I can no longer "reach" all notes from the drop-down menu (the folder icon) in the app, because it only displays the first few entries. 

![ss_simplenotes_android_bug_report_324x576](https://cloud.githubusercontent.com/assets/8035319/20462793/4ba244d8-af26-11e6-9092-3062e52f9362.png)

As you can see, the bottom radio button also does not display a name, but is an empty string.

I realize this may be by design, but it would help me if I could scroll through a list of all my notes, and be able to select and edit them in the future (instead of having to use `sqlite3` from the command line).

Is this something that you would consinder implementing?

**Comment by tibbi** [comment]
ah wow, it might not be scrollable indeed, havent thought of somebody having so many notes :) Ill maybe roll out a fast fix today.
