### ISSUE TITLE
"New note" button hinders text editing

### ISSUE THREAD

**Issue by Neftas** [SimpleMobileTools/Simple-Notes#30]
When I type a note and reach the end of the screen, the "new note" button (the orange button with the plus sign in it), makes it impossible to select the word under it:

![ss_simplenotes_android_button_324x576](https://cloud.githubusercontent.com/assets/8035319/20462931/9a784b0a-af28-11e6-8906-046afc60469c.png)

As a workaround, I keep several lines of empty space below my note just to keep this from happening, but that is not the most convenient solution, of course.

Is there a way this button could not be displayed when entering text? Other solutions to this problem would be fine as well, of course.

**Comment by mueller-ma** [comment]
In my opinion the button should allways be visible. Maybe make it transparent, when it hides text, but I don't know if this would be material design

**Comment by Neftas** [comment]
@mueller-ma I don't mind the fact that it hides some text so much, but I often make mistakes when I type (stupid software keyboard ;-) and then I want to select that word and change it. But when the button hides the text, I need create a couple of empty lines at the end of the note first in order to do so, otherwise I'll inadvertently click the "new note" button. It just disturbs my flow. I have no idea how other apps solve this.
