### ISSUE TITLE
Change caret color for higher contrast

### ISSUE THREAD

**Issue by WillRieske** [SimpleMobileTools/Simple-Notes#303]
The light-gray caret on the medium-gray note background is difficult to see, especially at an angle or for vision-impaired users. Recommend a brighter color and/or thicker caret width.

**Comment by tibbi** [comment]
The color comes from the system, Im not setting it manually. So dont really expect having it fixed anytime soon. I can keep it here though.

**Comment by tibbi** [comment]
should be improved in the next version 6.3.1
