### ISSUE TITLE
Complete data loss after export and crash

### ISSUE THREAD

**Issue by anescient** [SimpleMobileTools/Simple-Notes#321]
My notes are apparently permanently deleted. I exported text files then deleted the exported directory. On returning to Notes app it crashed. After starting it again all notes are gone.

[edit] update, see my comment below

In more detail:
I did an export all to text files (first time ever). A dialog appeared with two choices. I didn't expect it, and I accidentally tapped the first option before I could read any of it. I decided to redo the export to see what those options were. I deleted the folder I'd just created in the process, and then returned to the Notes application. It crashed immediately, and when I restarted it my notes were gone. I see no files under the application's /data/ directory, just an empty subdirectory called "files".

release 6.3.1, Android 8.1.0

**Comment by anescient** [comment]
I put off going back and trying the export again while I tried to figure out if I could get my data back.

I see now. The first option explicitly says the notes will be gone if I delete those files.

I strongly recommend changes to the UI, here. That is **not** what I would expect from an "export" action. I suggest it should be renamed and moved to the settings screen.

**Comment by tibbi** [comment]
Well that is currently the expected behaviour, no bug there. Ill see how could it be improved. Over a hundread thousand people are using the app daily and so far not a single person had such an issue. Thanks

**Comment by anescient** [comment]
Dude, one miss-tap fundamentally changed the app's storage and exposed its data.

It doesn't matter if a hundred *million* people haven't had this problem. Every single issue is experienced first by one user.
