### ISSUE TITLE
Data is lost when export fails

### ISSUE THREAD

**Issue by anescient** [SimpleMobileTools/Simple-Notes#322]
When exporting (single note or all notes), if there is a problem writing the file(s) the note(s) are lost.

The easiest way to reproduce this is to export to a directory that no longer exists:
Export note or notes, creating a directory for them
Delete that directory
Export again (notice the previous, now invalid path is still the destination), and select the first option "Update the file itself ..."
If exporting a single file, a message reports a FileNotFoundException. If exporting all, a message reports "Exporting some entries failed"

After this the application may fail in different ways.
Exiting and returning may result in a crash. Navigating notes or creating new ones may result in a crash. The notes will be gone after restarting the app.
Rather than crashing the app may continue to act normally, but notes will be lost after exiting and returning.

release 6.3.1, Android 8.1.0

**Comment by tibbi** [comment]
exporting has been drastically since then
