### ISSUE TITLE
[feature request] option to make widgets independant notes

### ISSUE THREAD

**Issue by I338** [SimpleMobileTools/Simple-Notes#323]
I don't know how hard it would be to implement, but it would be cool if there was a feature to make different instances of the widget be independent notes instead of just showing the same thing on all of them.
(I don't know if I was clear enough in describing what I meant, so I attached a picture)
![notes](https://user-images.githubusercontent.com/53239697/73902256-1483ec00-488d-11ea-9532-b7241391d242.png)

**Comment by tibbi** [comment]
it is already there, just upgrade to the Pro version
