### ISSUE TITLE
[Feature request] Allow selecting default storage location of new notes

### ISSUE THREAD

**Issue by aunwin** [SimpleMobileTools/Simple-Notes#324]
When creating new notes it is not possible to select the place this note is stored ad. This would be a nice feature to have, since it would allow automatically creating notes in a location that one can e.g. autoupload to a nextcloud or similar.

**Comment by tibbi** [comment]
It is a too advanced feature, dont really expect having that. One does not create new notes that often anyway.

**Comment by aunwin** [comment]
It is more about the fact that when creating new notes while others are automatically synct with a cloud, one forgets about the fact that newly created notes are possibly stored somewhere else

**Comment by tibbi** [comment]
instead of creating a new note in the app just get used to opening the files with some file manager and opening them in Simple Notes. Or just use the "Open file" option in Simple Notes.
