### ISSUE TITLE
[Feature request] Move done checklist items to bottom automatically

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [SimpleMobileTools/Simple-Notes#326]
When using the app as a shopping list, then it would be nice if this feature would be implemented. Only the relevant items would stay on top.

**Comment by tibbi** [comment]
there is already a "Move undone checklist items at the top" setting

**Comment by klawdhfzasjhaa** [comment]
Ok, we have a mix of bad (German) translation and wrong expectation here. I've tested with a checklist with three items: 1, 2, 3 and marked the second one to see what happens. Problem is, that the marked item does not go down instantly. Other apps behave like that, that's why I expected it to be the same with Simple Notes.

So, can you please reopen?

**Comment by tibbi** [comment]
it is supposed to be moved only at app reopening, like mentioned at the app settings title. I dont want to do it right after marking as done, I found it too confusing.

**Comment by klawdhfzasjhaa** [comment]
Instant "Move to bottom" is the default in most apps I guess. See https://play.google.com/store/apps/details?id=panama.android.notes. And I think it's like that also in Google Tasks, but I don't remember anymore..
I respect your choice. Maybe we simply wait and see, what others think and post here.
