### ISSUE TITLE
[Feature Request] / [Bug] Sharing special text crashes simple notes permanently, add ability to import multiline text input as separate checklist items

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [SimpleMobileTools/Simple-Notes#327]
App Version: 6.4.0
Source: F-Droid
Android: 9
LineageOS 16.0-20200205

A came across this issue when trying to import a shopping from another app via the share menu. The text is:

`Supermarkt - Supermarkt
- [ 1 ] O-Saft
- [ 1 ] Blätterteig 1 pkg.
- [ 1 ] Bananen
- [ 1 ] Äpfel
- [ 1 ] Tomaten
- [ 1 ] Gurke`

No dots in pasted text, only "-" (minus symbol).

Steps to reproduce:

- Share the text above via share menu and choose Simple Notes as target
- Choose "new note"
- Choose "Check list" and name note "Test", press "OK"
- App crashes instantly and one is unable to open it again.

You have to go to the Android Apps menu and delete whole storage of the app to use it again. Sure, all notes are lost this way.
_____
[Feature Request]
It would be great if Simple Notes would be able to create **one checklist item for each new line** from the shared text. Do you think it is possible to recognize the line breaks?

**Comment by tibbi** [comment]
can you specify which app are you sharing the given text from?
Please report just 1 thing per ticket.

**Comment by klawdhfzasjhaa** [comment]
Ok, shall I open a second one for the feature request?


> can you specify which app are you sharing the given text from?

It does not matter, which app you share it from. In Android 9 you can basically mark a text and choose "share" from the menu (besides cut, paste, etc.). You can even share the text from Simple Notes itself. It must be something **IN** the text.

**Comment by WoM4bLEjR** [comment]
Had the same Issue **at first** with app 'NewPipe' using 'Share with' function.

**Now**: Always by just opening Simple Notes (directly from a launcher) the app crashes.

my circumstances:
android 8.0 (unrooted) 
newpipe v 0.18.2
simple notes 6.4.0

Tried several 'simple notes' updates but nothing brought back serious health data logs :(  
(no backups until now - my fault 🤯 - are you planning a 'Simple Backup' 🧐?)

Can I help with logfiles? Where?
greets.

**Comment by tibbi** [comment]
I see, it happens only if you share the text into a Checklist item, not a casual plain text note. It should be fixed soon, then you can just upgrade the app and run it. Or to recover your notes try just creating widgets from the notes to see their content.
