### ISSUE TITLE
Text history issue when a note isn't empty

### ISSUE THREAD

**Issue by Maxime-J** [SimpleMobileTools/Simple-Notes#345]
From a clear state (i.e. without typing history saved),
if text is added to a non-empty note and back function is used afterwards,
it's bugged and could damage the text already present.

Recording here: [https://www.dropbox.com/s/o2wj8dguf9zt6hv/back_notes.mp4?raw=1](https://www.dropbox.com/s/o2wj8dguf9zt6hv/back_notes.mp4?raw=1)

**Additional info**
If text is added a the end of the note, there's an `OutOfBoundsException` error prompt :
replace (_value_ ... _value_) ends beyond length _value_

**Comment by tibbi** [comment]
what app version is that from?

**Comment by Maxime-J** [comment]
The latest release from this repo, 6.5.1
