### ISSUE TITLE
Jagged font rendering

### ISSUE THREAD

**Issue by wooque** [SimpleMobileTools/Simple-Notes#348]
Font rendering in notes are not as smooth as rest of the interface
![Screenshot_Notes_20200513-192007](https://user-images.githubusercontent.com/1936195/81844284-21307400-954f-11ea-9be0-84620179cfcf.png)

**Comment by tibbi** [comment]
what app version is that?

**Comment by wooque** [comment]
6.5.1, latest one from F-Droid

**Comment by wooque** [comment]
Also, I'm using Android 10 if that matters

**Comment by OpenWarp** [comment]
Same here. Android 9. Actually, it is tolerable in notes but gets painfully jagged and broken in the list as the grocery list in above example. Mine is even worse. The rest of the notes are okay, maybe a bit distorted but not as bad as the list. The font appears bigger in the list as if it were font rendering problem.
