### ISSUE TITLE
[ui] Switch notes with drop down menu instead of dialog

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Notes#35]
As in the first screenshot [here](https://play.google.com/store/apps/details?id=com.splendapps.splendo) (not an app I've used; I just looked up apps on gplay until I saw a screenshot that visually looked like what I'm talking about).

From the [material guidelines](https://material.google.com/components/dialogs.html#dialogs-simple-menus):

>**Disambiguation:** Simple dialogs display detailed options for list items or provide related actions. Simple dialogs can display the same content as simple menus. However, simple menus are preferred because they are less disruptive to the user’s current context.

The material guidelines are just that -- guidelines; they can be broken. In this case, though, they're totally right; switching notes isn't the level of importance that requires dialog-level disruption.

**Comment by tibbi** [comment]
I actually plan moving the notes into a viewpager, so its possible to swipe between them.

**Comment by smichel17** [comment]
If you have a lot of notes, that sounds like it could get cumbersome to cycle through. A navigation drawer is another option, although I prefer the drop down menu in this situation.

**Comment by tibbi** [comment]
updated the main view to a viewpager, the dialog is still there if somebody has many notes. Im leaving it like that for now.

**Comment by smichel17** [comment]
My main motivation for this is that most devices show 2 menu options as icons, and it's kind of awkward having `Rename` as an icon. Using a spinner instead a menu item to change notes adds room for one more.

That said, I do like the viewpager quite a bit and will probably use it more often than the spinner, and they would look a bit odd together. So, I'm going to start by just implementing the spinner and see how I like it, but if it feels as weird as I'm anticipating, I'll have more work to do before it's merge-ready. We'll just have to see.

**Comment by tibbi** [comment]
well you can try it, but I dont guarantee I will like it ;)

**Comment by smichel17** [comment]
Yeah, I'm not sure I will like it, either :P

I'll just try it and see how it goes. Worst case scenario I don't like it either and end up throwing it away,  but I learned something about spinners.

**Comment by smichel17** [comment]
Unrelated: It seems like the kotlin android extensions are not null safe, so while I like avoiding `findviewbyid`, I'm not sure I like the extensions overall.

**Comment by smichel17** [comment]
Related: I have a working draft, https://github.com/SimpleMobileTools/Simple-Notes/compare/master...smichel17:spinner

NB: This is a WIP (I still need to fix styling and make a couple small bugfixes). I only committed so you can check it out; I am planning on rebasing, so just know that if you pull.

**Comment by smichel17** [comment]
@tibbi I'm going to stop here until you get a chance to try it out and see if you'd be interested in merging.

**Comment by tibbi** [comment]
well I honestly dont like it, it doesnt feel like an android app at all

**Comment by smichel17** [comment]
That's a good point. I have an idea for a UI that will feel more like android. I'll make a quick mockup when I'm off mobile in a sec.

**Comment by smichel17** [comment]
@tibbi Thoughts on this?

![mockup](https://cloud.githubusercontent.com/assets/6563664/21746454/ab7f5f0e-d513-11e6-9236-d446c2c29642.jpg)

**Comment by smichel17** [comment]
Note: I'm not attached to this particular design. I am just trying to find a way to move the note selection option out of the menu, with a secondary goal of providing a better experience for people who prefer list navigation to swiping.

**Comment by tibbi** [comment]
I dont want any screens before the actual note. I like the current way, theres nothing simpler than a swipe. 99% of users have less than 3 notes, so it really doesnt make sense to complicate it and pretend its a huge app.

**Comment by smichel17** [comment]
>99% of users have less than 3 notes

If that's true, then I agree that menu navigation is not important. I have 7 notes, although I use only 3 regularly.

**Comment by mueller-ma** [comment]
The current design looks perfect to me:

1. For people with a few notes they can swipe (pretty fast)
2. For people with many note they can use the folder icon

**Comment by smichel17** [comment]
@mueller-ma I linked a branch above that's got my first attempt at a solution. @tibbi doesn't like it and I'm not going to force the matter, but that's what I'd do if I had my choice. Note that it's not production ready (there's still a couple bugs and theming to do), but it's ready enough to play around with.
