### ISSUE TITLE
app crashes on start, need a way to backup notes prior to uninstalling

### ISSUE THREAD

**Issue by yepyepyep4711** [SimpleMobileTools/Simple-Notes#352]
hello,

I'm on 6.5.2.

My app crashes on start, regardless of whether I use the app shortcut or the widget to start it. Widgets display the preview of the text, but downgrading with F-Droid doesn't work (Error -25, older version code than currently installed package, this sounds logical but I don't know how to get around it).

I don't want to lose the content.

Thanks for any help

**Comment by tibbi** [comment]
upgrade to 6.5.3, it should be fixed already

**Comment by yepyepyep4711** [comment]
That was fast. It worked. Thanks a lot!
I hope there will be a way to access the content without the app in the future, in case development stops at a later point in time
