### ISSUE TITLE
Give notes a filesystem path to allow syncing

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Notes#354]
Unless I am missing something, the currently edited notes are not available at a filesystem path. They seem to be saved in an opaque database, amd need to be exported. Which is a deal-breaker if you want your notes backed up.

It would be better if they were saved straight to the filesystem. Then users could just point a sync tool at them. Surprisingly few notes apps seem to do this, I do not understand why.

Thanks for considering.

**Comment by tibbi** [comment]
you can already export notes into files, or use the Open File menu item and enable syncing

**Comment by Friptick** [comment]
@tibbi But Open File is an **import** function. You can modify and sync the source file all you like, the Simple Notes **copy** will not be affected. And, as I mentioned, that **copy** is nowhere to be found in the filesystem. I believe you understand all this very well already, but still you chose to deny the point I was making.

This is your app, of course. Perhaps just saying "No, i don't care, go away" would have been a more honest response. I just was trying to help you make the app better.
