### ISSUE TITLE
Syncing no longer works?

### ISSUE THREAD

**Issue by ClockGen** [SimpleMobileTools/Simple-Notes#356]
I haven't used simple notes for some time, but before there was a (cruicial to me) function to synchronize notes with the file system. The option is no longer there, when I'm trying to save or open notes it just opens default android SAF interface instead of custom simplemobiletools one, and without any options or dialogues to sync it. I couldn't find any options or settings either.

**Comment by tibbi** [comment]
what app version and Android OS version do you have?

**Comment by ClockGen** [comment]
@tibbi I have pro version 6.5.3 from F-Droid. My android version is 9, rom is LineageOS 16.0.

**Comment by tibbi** [comment]
try granting "Storage" permission in the device settings, some new menu items should appear. I want to eventually remove the permission and rely on the new storage access framework.

**Comment by ClockGen** [comment]
Yes, that worked, thank you. I hope that all the functions (like importing folders and sync) will remain when you switch to SAF.
