### ISSUE TITLE
Feature request: Add option to export multiple notes at the same time.

### ISSUE THREAD

**Issue by GodDonovan** [SimpleMobileTools/Simple-Notes#359]
Title.

**Comment by tibbi** [comment]
what app version are you using? It should already be there. If it isnt, try granting the Storage permission at the device settings manually.

**Comment by GodDonovan** [comment]
Oh really? I wasn't aware of this, sorry.

I am on 6.5.3.74

It turns out that the Storage permission was not granted. Changing this has fixed the issue.

Is there a way to select which notes can be exported?

Thanks for your help.

**Comment by tibbi** [comment]
well that button has been removed intentionally as Im trying to move away from the Storage permission altogether. The app soon wont be allow to request it, it will be really limited to what apps can ask for it. Batch exporting will be made more difficult so I kept only the single exporting there.

**Comment by GodDonovan** [comment]
Won't be allowed to request it? Is this related to some sort of restriction that will be implemented in Android 11?

**Comment by tibbi** [comment]
not sure when exactly will it be added, it seems to be delayed already
