### ISSUE TITLE
[feature request] encrypt the note

### ISSUE THREAD

**Issue by nhy42** [SimpleMobileTools/Simple-Notes#365]
Add the capability to encrypt the note (with a password or if possible with fingerprint) to have secure notes.

**Comment by nhy42** [comment]
I understand well that encrypt the entire phone is the solution, but it doesn't prevent others app with storage permission to access it when the phone is turned on...
Also, if someone as an access to the unlocked device, he can reads the note. If you don't want to implement encryption, maybe at least can you do a fingerprint/password locking, as in Simple Galery ?

**Comment by tibbi** [comment]
ye, thats on the roadmap. Other apps cannot really get to the notes through it, they are stored in the internal apps database.

**Comment by Kohoshi12** [comment]
> I understand well that encrypt the entire phone is the solution, but it doesn't prevent others app with storage permission to access it when the phone is turned on...
> Also, if someone as an access to the unlocked device, he can reads the note. If you don't want to implement encryption, maybe at least can you do a fingerprint/password locking, as in Simple Galery ?

Is it possible to encrypt the android system? I know that was possible before, but not now. And an open source cryptograph software on android could be interesting.

**Comment by qazip** [comment]
Ya, this would be fantastic. I would also like to be able to "secure" some notes, that is, put them behind a pin or fingerprint or whatever.

**Comment by tibbi** [comment]
some protection will be added in 6.8.0. Biometric lock has been changed recently on some Android versions, it needs more work.
