### ISSUE TITLE
Allow deleting a member of a checklist

### ISSUE THREAD

**Issue by ellebue** [SimpleMobileTools/Simple-Notes#374]
Now it is only supported to cross out elements of a list but not to delete them. It would be nice to delete elements so that the list not becomes infinitely large.

**Comment by tibbi** [comment]
you can select them by long pressing and using the top Menu -> Delete, just like in other apps.

**Comment by ellebue** [comment]
Thanks die that gibt but in the top menu I can not see the delete button (as you can see in the picture). Because I tried it I know it is in the right corner.
![Screenshot_20201023-104538](https://user-images.githubusercontent.com/67577867/96977374-4d4c1a00-151d-11eb-8dac-b703e697a176.png)

**Comment by ellebue** [comment]
Thanks die that gibt but in the top menu I can not see the delete button (as you can see in the picture). Because I tried it I know it is in the right corner.
![Screenshot_Notes](https://user-images.githubusercontent.com/67577867/96977612-9dc37780-151d-11eb-9fe9-4f9d8629a881.png)

**Comment by tibbi** [comment]
guess you just changed your colors lately. Restart the app for the colors to be applied properly.
