### ISSUE TITLE
In Black and White mode the grab bars are black

### ISSUE THREAD

**Issue by doozan** [SimpleMobileTools/Simple-Notes#377]
In black and white mode, the grab bars are invisible against the black background.  Is it possible to make the grab bars match the selection color?

![test](https://user-images.githubusercontent.com/409080/99397111-838d7700-28da-11eb-9ac7-24d3a6b4bd0a.jpg)

**Comment by tibbi** [comment]
that is not easy to customize at all, has to be preset in some theme. Anyway, it is a generic issue that affects basically all apps, so Ill close this issue.

**Comment by doozan** [comment]
I only experience this issue in Simple Notes, every other app with a dark theme uses the same color for the highlight and the grab bars.

**Comment by tibbi** [comment]
I mean other apps from our suite, forgot to close it..
