### ISSUE TITLE
Two lines in long description with one sense

### ISSUE THREAD

**Issue by bac1** [SimpleMobileTools/Simple-Notes#386]
1) "It is user friendly and contains absolutely no ads or unnecessary permissions - no strings attached. It is fully opensource, provides customizable colors which can be adjusted with quick and fast tweaking."

2) "Contains no ads or unnecessary permissions. It is fully opensource, provides customizable colors."

Maybe the first of these two needs to be changed or removed?

**Comment by tibbi** [comment]
I use a bit different long descriptions on Google Play, which is optimized for keywords. It might not be updated on Github properly.

**Comment by bac1** [comment]
@tibbi translating long description is usless?

**Comment by tibbi** [comment]
well current Google Play translations are from other source in some languages, not from Github. Im not using some of them anywhere now, but that might change.
