### ISSUE TITLE
Undo issues, how to recover text?

### ISSUE THREAD

**Issue by riveravaldez** [SimpleMobileTools/Simple-Notes#390]
Hi, sorry if this is not the place for this: I had some text in a note and some buggy undo steps caused the lost of big parts of the text, I'm trying to recover it. Where and how Simple Notes saves the text and undo history (if so)? If the undo action doesn't recover the text is there any other way to do it?
Any help would be extremely appreciated.
Thanks!

**Comment by tibbi** [comment]
Hey, it is stored only in a variable while the app runs, you cannot really recover it from other sources. Ive tested Undo and it really works weird, not sure when it broke. It used to work well, will take a look at it to prevent future issues. Thanks

**Comment by riveravaldez** [comment]
Thanks a lot to you, Tibor, for all your awesome work and for the clear, informative and astonishingly quick response.
Best regards!

**Comment by Maxime-J** [comment]
Thanks @tibbi!
it fixes #345, kind of a long time issue.
I'll close that one.
