### ISSUE TITLE
App crashes while trying to import a checklist note

### ISSUE THREAD

**Issue by JuliaSzulc** [SimpleMobileTools/Simple-Notes#392]
As in the title title. I exported a checklist note from the app and then tried to import it but it still crashes and nothing is imported.

App version: 6.6. Pro (F-Droid)
Android 7.0

**Comment by tibbi** [comment]
can you maybe send the sample file? Just open it with any text editor and filter out whatever you dont want to share

**Comment by JuliaSzulc** [comment]
[Checklist.txt](https://github.com/SimpleMobileTools/Simple-Notes/files/5831987/Checklist.txt)
