### ISSUE TITLE
Open File doesn't work correctly with check lists

### ISSUE THREAD

**Issue by Mrnofish** [SimpleMobileTools/Simple-Notes#397]
1. Export a checklist from Simple Notes.
2. Open File and select the .txt file you've just now exported

The resulting note shows a check list of empty items.

Tap-n-hold an item and then Rename causes the app to crash.

![Screenshot_20210130-164941_Notes](https://user-images.githubusercontent.com/28036193/106361000-d7c1c800-631b-11eb-912a-618069246489.png)

[Stardew.txt](https://github.com/SimpleMobileTools/Simple-Notes/files/5898240/Stardew.txt)

**Comment by tibbi** [comment]
Just update to 6.6.1, should be fixed already

**Comment by Mrnofish** [comment]
I **am** using 6.6.1.

**Comment by tibbi** [comment]
Try reinstalling the app, then checking with exporting how does the file look like. If it contains "a", "b", "c" and similar useles labels, or "isFalse" etc. You will see what I mean. Try also using Share, to see if it behaves the same way.

**Comment by Mrnofish** [comment]
I see what you mean, now, the old file was probably exported by an older version that had the bug.

Exporting from 6.6.1 looks OK, using both Export and Share. I'll have to fix my old notes in order for them to import correctly.

Thanks for the help.

**Comment by pmartycz** [comment]
> Try reinstalling the app, then checking with exporting how does the file look like. If it contains "a", "b", "c" and similar useles labels, or "isFalse" etc. You will see what I mean. Try also using Share, to see if it behaves the same way.

I was able to fix faulty `a` `b` `c` export with
```bash
mkdir out; for f in *.txt; do [ "$(file -b --mime-type "$f")" = application/json ] && jq -c 'map(with_entries(.key |= if . == "a" then "id" elif . == "b" then "title" elif . == "c" then "isDone" else . end))' "$f" > "out/$f"; done
```
Then import `out/` folder (requires Storage permission)
