### ISSUE TITLE
Update from 6.6.0 yo 6.6.1 broke my checklists

### ISSUE THREAD

**Issue by bikepunk** [SimpleMobileTools/Simple-Notes#402]
Running Simple Notes on LineageOS 16.0

Update from 6.6.0 yo 6.6.1 broke my checklists, they items description disappeared. and the ticks are "locked". I cannot change them any longer.

(The pity is that the downgrade function is not working in F-droid )

**Comment by tibbi** [comment]
Right, there was a glitch during the update, sadly you wont be able to recover the items :/ It wont happen in the future though, it was caused unintentionally by changing something. Sorry for that

**Comment by bikepunk** [comment]
ok, too bad. Hopefully I had nothing capital in those checklists.

Thanks for your great apps BTW. I love them.
