### ISSUE TITLE
Unwanted space after comma and quote marks

### ISSUE THREAD

**Issue by Kohoshi12** [SimpleMobileTools/Simple-Notes#407]
Always that the user write a word between two quote marks, then a comma and write another word inside quotation mark, the first letter of the second word will receive a space automatically from the quotation mark. For example, if the user write something like "Word", "Another word", the second word after the quote mark will receive a space, so will be like "Word", " Another word". This just happen once after the user write a comma and does not happen with simple quote marks.

**Comment by tibbi** [comment]
Isnt it caused by your keyboard? We definitely arent adding anything like that.

**Comment by tibbi** [comment]
yep, it is keyboards doing that
