### ISSUE TITLE
Folder based sync ?

### ISSUE THREAD

**Issue by Mrnofish** [SimpleMobileTools/Simple-Notes#411]
Would you consider adding folder based sync?

Basically, the application would just need to automatically export all of its notes to a folder in the file system, whenever changes are made (possibly within a grace period). An external app could then take care of the actual folder syncing, managing conflicts, etc.

It would be nice if the export also included plain text versions of the files, so they can be viewed easily in any editor that doesn't support JSON.

**Comment by tibbi** [comment]
dont expect having it. File functions will be weakening as such apps wont be able to get the Storage permission anymore soon.
