### ISSUE TITLE
Feature request: have an option to show the dragging buttons for each list item permanently

### ISSUE THREAD

**Issue by stephan75** [SimpleMobileTools/Simple-Notes#412]
There is one feature in my so far used to-do app "Simplest Checklist" by JakiganicSystems (last update in 03/2014) that I am missing in SimpleNotes:

The elements that are used to drag one list item up or down manually is **_always_** shown there, 
and I like this very much because priority of my todo items change quite often.

See screenshot:
![image](https://user-images.githubusercontent.com/5250044/113921957-fe522280-97e6-11eb-98ba-49f319b5a6a5.png)

So far in SimpleNotes it is nedded to long press an item before you can drag it up or down.

Is it possible to have an option in SimpleNotes settings whether the dragging buttons are
a) shown permanently (thus usable instantly) OR 
b) only when user does a long-press on an item?

**Comment by tibbi** [comment]
I dont want to add it, it looks weird and isnt needed often

**Comment by fabian-thomas** [comment]
For anyone arriving here in search for this feature:
Check out [my fork](https://github.com/fabian-thomas/Simple-Notes-Simple-Drag) with code by @leafar-tb.

For details on the current state check the referenced pull request.
