### ISSUE TITLE
Remove "Please Rate This App" pop-up

### ISSUE THREAD

**Issue by sasukeiscool** [SimpleMobileTools/Simple-Notes#415]
This pop-up is annoying so please remove it.

**Comment by CatKasha** [comment]
I have this pop-up too in F-Droid version of the app (6.7.1), its not that annoying because its show up rarely, but i little bit not understand why this pop-up ships with app that not have internet connection
Also i seem to have seen this pop-up in Simple Gallery too (but im not sure)

**Comment by tibbi** [comment]
just press a star and it wont show up again
