### ISSUE TITLE
Text gets strangely duplicated at the end of the note

### ISSUE THREAD

**Issue by masscream** [SimpleMobileTools/Simple-Notes#423]
Hello, this bug must have started some versions ago, because I consider myself a long-term user but I have never experienced this before. Bad news is that I don't know how to replicate, at first I thought that the cause may be that my note file (I use export and link function) has become too large with the time, however then I discovered this phenomenon also in some of the smaller (just a few lines) file. I was able to replicate the bug one day when I was opening the app and note via the widget on the desktop, however now when I do it again, it does not cause anything. The example is following: I put the following text at the end of the note

"Testovací poznámka, pro nahlášení na GitHub. Toto je testovací text." and here are the screenshots what it did with the time... You may ignore the note "ůle" since this is the replication of the part of my notes. And at the end I put "123" to got it replicated again now, without success.

![Screenshot_20210610-081414_Lawnchair](https://user-images.githubusercontent.com/11753248/121475255-75618e00-c9c5-11eb-8806-671c0db9de80.jpg)
![Screenshot_20210610-081424_Lawnchair](https://user-images.githubusercontent.com/11753248/121475263-77c3e800-c9c5-11eb-8afd-fb3d4065c103.jpg)
![Screenshot_20210610-081432_Lawnchair](https://user-images.githubusercontent.com/11753248/121475267-7a264200-c9c5-11eb-8b00-a10b488cf015.jpg)

**Comment by masscream** [comment]
I have figured out what it really causes. It's anytime I delete any text in the middle of the note / file, it strangely modifies the end for some reason.

**Comment by tibbi** [comment]
what app version are you using? Tell some simple steps for reproducing please.

**Comment by masscream** [comment]
6.8.0 Pro@F-Droid
Tried following and it worked:

1. Created a new note and wrote some text, a few lines with spaces.
2. Exported as a file .txt (if the note gets updated <=> update file), the issue did not occur without this step (but tested only 1x)
3. Deleted random line of text and/or space everywhere from the middle (just not the last one), ended the app by minimizing and pulling away
4. Next time I opened the note the last line was duplicated.
5. Worked several times, I just deleted any line/text from the body of the file

**Comment by tibbi** [comment]
can you reproduce it with some notes without accents or diacritics too? I mean note without á, í or emojis.

**Comment by masscream** [comment]
Yes, it can be reproduced while using normal plain text only - without diacritics too.

**Comment by tibbi** [comment]
should be fixed in 6.8.1
