### ISSUE TITLE
Preview bottom of the checklists on reopen

### ISSUE THREAD

**Issue by techxidize** [SimpleMobileTools/Simple-Notes#440]
I have checklists that has hundreds of items for some work, but everytime screen goes off or I relaunch, I need to scroll so much to get to bottom.

Best would be placing a settings option:

"What to preview on checklist notes reopen"

with three selections

1. First unchecked items 
2. Last unchecked items 
3. Last checked items

![5f795b3e-f92d-4193-a8cd-bac6a2b9a26c](https://user-images.githubusercontent.com/54729767/130431548-ab7c69ce-5db3-4d56-9b0b-8ed953f4d4e8.png)

**Comment by tibbi** [comment]
the app isnt really made for hundreads of checklist items, I dont want to add that

**Comment by techxidize** [comment]
Fair
