### ISSUE TITLE
Button "add new item" hides buttons to toggle checklist item

### ISSUE THREAD

**Issue by MrChocolatine** [SimpleMobileTools/Simple-Notes#443]
Before posting this issue I searched but I haven't found any other issue similar to mine.

### My device

Google Pixel 4a 5G

### The issue

1. Create new note "Checklist
1. Add <ins>at least</ins> 14 items to the note
1. The button "Add new checklist items", at the bottom right of the screen, hides the buttons "❌ / ✅" of the last item

### Proposed solution

Simply moving the button "Add new checklist items" to the header, alongside the buttons "Open note", "Add a new note" and "More".

**Comment by MrChocolatine** [comment]
To me this issue is more a bug than a "feature request" 🤔 .

**Comment by bigConifer** [comment]
Just another solution might be to add some botton margin to the checklist sheet.

**Comment by peake** [comment]
> Just another solution might be to add some botton margin to the checklist sheet.

👀 This is how the FreshBooks app does it and it's very elegant. Lists scroll far enough so that the last element is above (vertically) the floating button 👍

**Comment by bigConifer** [comment]
In fact this ticket is not a feature request but a bug report and it's still not fixed.

**Comment by bigConifer** [comment]
> it's very elegant. Lists scroll far enough so that the last element is above (vertically) the floating button

![20220122_220227](https://user-images.githubusercontent.com/64743731/150655708-d2dc4a9b-f3d5-4c88-9b41-a6867cd0759c.jpg)

Here is how Firefox for Android does it. I think it should be easy to implement...
