### ISSUE TITLE
Fix exporting notes to files it "wt" mode is not supported

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#444]
A guy lost his note this way. He chose syncing note to the exported file, but at exporting he got this error and the note disappeared.
![Screenshot_20210907-091706](https://user-images.githubusercontent.com/528931/132303076-8c6053b9-24c3-427c-8b32-26f92ef7e8c0.png)

**Comment by qwertyfinger** [comment]
Seems like this is the problem specifically with the Google Drive storage, and using `rwt` mode fixes this: https://github.com/itinance/react-native-fs/pull/837#issuecomment-776677509.

I was able to reproduce this error when saving to Google Drive but my text did not disappear. From the code I see why it might disappear, although not clear why it does not happen for me then.
