### ISSUE TITLE
Bug: Widgets: Corners rounded even though corner radius = 0dp

### ISSUE THREAD

**Issue by Jonta** [SimpleMobileTools/Simple-Notes#449]
- Android 10
- Nova launcher 7.0.49
- Home screen
- Widgets
- Corner radius: 0dp

**Comment by tibbi** [comment]
Corner radius customization isnt even in our app yet. If Nova has some customization, it is their job to handle it

**Comment by Jonta** [comment]
> Corner radius customization isnt even in our app yet. If Nova has some customization, it is their job to handle it

@tibbi Makes sense

But happens in Moto App Launcher as well (Motorola Moto G7 Power), and didn't find a setting for it there

Nova affects the corner radius of other widgets (Google Keep, Tasks.org, Google Calendar)

```
$ git grep rounded
CHANGELOG.md: * Added rounded corners at the widget
CHANGELOG.md: * Added rounded launcher icons for Android 7
fastlane/metadata/android/en-US/changelogs/72.txt: * Added rounded corners at the widget
$ git log --all --grep='rounded'
commit ae0ac642780f86bc45e0663e3d1e12219c368071
[…]
```
That commit adds
```
android:src="@drawable/widget_round_background" />
```

Does it round a different part of the widget? =)

**Comment by tibbi** [comment]
we do have rounded corners, I meant that we do not have it customizable yet
