### ISSUE TITLE
Req: Widget changes after they've been created

### ISSUE THREAD

**Issue by Jonta** [SimpleMobileTools/Simple-Notes#450]
- Colours
- Which note is displayed
- Typeface (serif, sans-serif, monospace when that comes along)

Right now it looks like the only way to do it is to create a new widget, and I know from my use of https://github.com/tasks/tasks/ that I like being able to tweak existing widgets. =)

**Comment by tibbi** [comment]
different widgets can show different notes and widget handling is already complicated enough, so I dont want to change the current behaviour. You can already customize existing widget if only one exists.

**Comment by Jonta** [comment]
Makes sense. Unsure of where you draw the line for "Simple". =)
