### ISSUE TITLE
Crashes after "skip upgrade" from 1.18 to 1.22

### ISSUE THREAD

**Issue by heyc** [SimpleMobileTools/Simple-Notes#46]
Hi,

after upgrading from version 1.18 to version 1.22 (both downloaded via F-Droid) Simple-Notes crashes on startup.  I did _not_ install version 1.19, 1.20 or 1.21 before I installed 1.22.

On the latest FireOS release (after some failed attempts to downgrade Simple-Notes), the presumably relevant logcat line was:

    Caused by: android.database.sqlite.SQLiteException: no such column: type (code 1): , while compiling: SELECT id, title, value, type FROM notes ORDER BY title COLLATE NOCASE ASC

 I reproduced this crash on Android 4.2: after installing version 1.18, I added a line to the general note and added a note that also contains one line. Finally, I removed Simple-Notes from the task list, upgraded to version 1.22, ran Simple-Notes and noticed that it crashed.

This bug would be very unfortunate if I wouldn't have created some "backups", i.e., screenshots.

Regards
Carsten

**Comment by tibbi** [comment]
ah cmon, that bug will not affect anyone else :)

**Comment by heyc** [comment]
* Tibor Kaputa [2016-12-09 00:07 -0800]:
> ah cmon, that bug will not affect anyone else :)

If this is true, then it's because you don't have much users yet that
use this software for more than six weeks - not because users don't do
"skip upgrades".

JFTR, the downgrades I mentioned are completely unrelated to crashing,
I only mentioned them because the logcat was done after trying to fix
the crash by downgrading.

Btw., the plus button to add a new note would ideally be in the bar
where rename, share and the other icons are; and being able to insert
a literal tab if the keyboard contains a tab key would be helpful.

**Comment by tibbi** [comment]
okay thanks for the logcat line, upgrades should be fixed with the next version. Ive also created an issue for adding the literal tabs.

**Comment by heyc** [comment]
* Tibor Kaputa [2016-12-09 10:12 -0800]:
> okay thanks for the logcat line, upgrades should be fixed with the
> next version. Ive also created an issue for adding the literal tabs.

Thanks, for both :)

I noticed that the tooltip of the leftmost icon (the one that can be
pressed to show the "Pick a note" box) is "Share" - this does not seem
to be correct.

**Comment by tibbi** [comment]
oops thanks, fixed it :)

**Comment by gityeti** [comment]
Hello, thanks for your work, I like your app.
I had the same problem/bug. When upgrading from an older version to the latest, on F-Droid, it crashes when starting. Couldn't get it start. 

> after upgrading from version 1.18 to version 1.22  Simple-Notes crashes on startup. I did not install version 1.19, 1.20 or 1.21 before I installed 1.22.

It seems to me to be the same problem. I'm running android. Of course I could not recover my notes! (backup of course) I had to remove SimpleNotes and reinstall it.
Regards
