### ISSUE TITLE
New note button

### ISSUE THREAD

**Issue by bigConifer** [SimpleMobileTools/Simple-Notes#469]
Please put the "Create a new note" option at the top of the note picker dialogue, so that the user can quickly open a new note (on startup), even if more than a dozen notes exists.

As a side effect, this "new note" option is then no longer needed in the menu bar. 
So the "+" button in the menu bar can be removed, since anyway it is only shown for checklists (because there is no search button) or in landscape mode, which IMHO is really counterintuitive.

~Thus, also issue https://github.com/SimpleMobileTools/Simple-Notes/issues/443 could be resolved by replacing the "add checklist items" floating button with a new "+" button in menu bar.~

**Comment by bigConifer** [comment]
> duplicate of #443

Honestly not.
This one here is about the "new note" button, https://github.com/SimpleMobileTools/Simple-Notes/issues/443 is about the "add cheklist items" button. 
It's only related at some point and therefore I mentioned it.

So please reopen it

**Comment by tibbi** [comment]
the New note button is there at the bottom of the note picker, I dont want to move it to the top. All apps have such buttons at the bottom and thats what makes the most sense.

**Comment by bigConifer** [comment]
Ok, thanks for explaining.

But apart from other apps, what is the benefit of the current position?
If it's pinned at top, it has a fixed position an users don't need to scroll or search for it, what will be an improvement in workflow.
Might rename it as "open a new note", so that it fits better to the top title...

Furthermore this issue is also about the existing "+" button in the menu bar, its inconsistencies and the question if it's redundant.

**Comment by bigConifer** [comment]
> this issue is also about the existing "+" button in the menu bar

> it is only shown for checklists (because there is no search button) or in landscape mode, which IMHO is really counterintuitive.

This part will be fixed by #498.
