### ISSUE TITLE
Deleting "General notes" confuses Simple-Notes

### ISSUE THREAD

**Issue by heyc** [SimpleMobileTools/Simple-Notes#47]
Deleting the "General notes" confuses Simple-Notes - tested on version 1.19 (the first release with this feature) and 1.22.

To reproduce this issue this steps can be used:

 - ensure that you have no real notes saved in Simple-Notes
 - delete the apps data and cache
 - run Simple-Notes
 - type "Some text" as the general note's text
 - add a new note named "Asdf"
 - type "Asdf" as the note's text
 - switch to the general note
 - select "delete note" in the menu and click on "ok"

Now the text of the note "Asdf" is shown in the same way as the general note is shown, i.e., the note's name is not shown and the note can not be renamed. Given that the note is still internally named "Asdf" and the general note has vanished, I suspect that adding a general note again using only the UI is either impossible or very tricky. 

I missed this feature, or rather one that empties the general note (and possibly could also be named "empty general note" instead of "delete note"), in version 1.18 and still think that it would be very useful.

**Comment by tibbi** [comment]
well thats pretty much the whole idea of the apps, the simplicity and not bloating the UI with useles things. Whats the point of displaying the note's name, if there is only 1 note? I dont really want to change it by showing unnecessary things.

**Comment by heyc** [comment]
* Tibor Kaputa [2016-12-09 00:13 -0800]:
> well thats pretty much the whole idea of the apps, the simplicity and
> not bloating the UI with useles things. Whats the point of displaying
> the note's name, if there is only 1 note? I dont really want to change
> it by showing unnecessary things.

My point was not that the UI should be changed, but that deleting the
"General note" should not be possible.  (Clearing it would be helpful,
though, since it saves users from hitting backspace hundreds of times)
