### ISSUE TITLE
Trash button deletes entire list without asking

### ISSUE THREAD

**Issue by konomikitten** [SimpleMobileTools/Simple-Notes#482]
I just managed to trash my entire checklist by accidentality hitting the trash icon that I've circled below in my screenshot, please add a confirmation dialogue before deleting the entire list when pressing this button. I lost over 40 items.

![2021-11-25-184712](https://user-images.githubusercontent.com/12713710/143400770-152f8016-29e2-49bb-8768-b5b39a4bcac8.png)

**Comment by Aga-C** [comment]
If this will be done, there should be an ability to turn off the confirmation dialog in Settings to have it working the same way as it's now. I'm used to having it like it is now, since it's not removing the whole note, just done items, and removes them quickly.

**Comment by tibbi** [comment]
well we should definitely add a confirmation dialog there and maybe change the icon too, the trashbin icon resembles deleting the whole note to me

**Comment by Aga-C** [comment]
I thought about this kind of option since there is a similar one in Simple File Manager and Simple Gallery regarding deleting items.
