### ISSUE TITLE
cannot navigate to other note after editing a text note

### ISSUE THREAD

**Issue by h2dden** [SimpleMobileTools/Simple-Notes#483]
so I am editing a note, press back button and the keyboard hides.
But the note is still in edit mode: I can see the cursor.
If I try navigating to another note by swiping left or right nothing happens
If I press back button again to exit edit mode, the app exits: I need to open the app again and navigate to another note

**Comment by h2dden** [comment]
I am using version 6.10.0 pro

**Comment by tibbi** [comment]
what OS version are you using?
