### ISSUE TITLE
auto sort check lists by status

### ISSUE THREAD

**Issue by h2dden** [SimpleMobileTools/Simple-Notes#485]
the current option of sorting check lists by status is awsome, but I have long lists and the point with check lists is to keep track of entries still to check out.
The current setup asks for scrolling up and down several times to spot the remaining active entries: annoying
It would be nice to club to the top the active entries and every time an entry status is changes to have the list reordered by status
This way the remaining active entries are always on top and easy to spot

**Comment by tibbi** [comment]
you can already enable moving done checklist items at the bottom in the Sort by dialog
