### ISSUE TITLE
startup screen: clear list of notes

### ISSUE THREAD

**Issue by h2dden** [SimpleMobileTools/Simple-Notes#486]
the current setup works for a few notes: you open the app and swipe left/right to the note you need to read
But if you have 10 lists or more, getting to the one you need is a challenge: is not like you swipe quickly to the right position... annoying
It would be nice for the startup screen to show a scrollable vertical list of notes, that is a list of titles which upon clicking gets you to the right note quick and easy

**Comment by h2dden** [comment]
I might add that it would ne nice to be able to re arrange the notes in a prefered way

**Comment by tibbi** [comment]
you can already enable "Show a note picker on startup" in the app settings
