### ISSUE TITLE
simpler checklist design

### ISSUE THREAD

**Issue by h2dden** [SimpleMobileTools/Simple-Notes#487]
I like to design philosophy: simplicity
the visual elements in the checklist are not in line with the philosophy
I find the red and green icons (X and checked) on the right side visually unsettling: it even triggers my anxiety :)))
make it simple and remove those, more so as these are redundant: it is clear when an entry is active or not by striking through and greying out 
It is more than enough and it is simple

**Comment by tibbi** [comment]
I dont plan removing that
