### ISSUE TITLE
Allow moving done checklist items to the bottom in custom sorting mode

### ISSUE THREAD

**Issue by bigConifer** [SimpleMobileTools/Simple-Notes#497]
For checklists, please allow users to decide if they want to "move done checklist items to the bottom" in custom sorting mode too.
I don't see, why this option (see right picture) should not be equally available for all sorting modes.

<p>
  <img src="https://user-images.githubusercontent.com/64743731/150655851-7e657d41-5d1d-4658-ba67-beec7eb55425.jpg" width="45%" title=""/>
  <img src="https://user-images.githubusercontent.com/64743731/150655871-86c5bd3a-543d-4d5c-9d5f-e46f99f7765b.jpg" width="45%" title=""/> 
</p>

**Comment by tibbi** [comment]
that would be confusing. Custom means Drag & Drop, nothing automatic.

**Comment by bigConifer** [comment]
Is there any argument against having that option for users who understand it's value and are not confused by that?
It would be fine to set the option to disabled by default in custom mode, but please let users decide if they want to enable it.

**Comment by bigConifer** [comment]
FYI there are valid use cases for this. Many users want to sort their open tasks by priority instead of name and therefore enable custom sorting mode. But as soon as a task is done it's priority is marked down instantly. 
All of these users currently have to move their done items down manually. This is exactly the use case for automatic down moving. Nothing confusing with that.

**Comment by tibbi** [comment]
not many users, you are the only one that reported it

**Comment by bigConifer** [comment]
> you are the only one that reported it

No, in fact I think #485 requested the same thing, but he/she stated it not clear enough so that you misunderstood it.

If you would at least leave this ticket open as a feature request, we could wait for comments from other users.

Furthermore it's only an issue since Oct 2021 (#462, #464) before of that it worked as expected.
