### ISSUE TITLE
[Feature Request] Daily-resetting checklists

### ISSUE THREAD

**Issue by BloodRaven0** [SimpleMobileTools/Simple-Notes#513]
Adding the option for a certain checklist to reset daily gives the opportunity to track and help build good habits (or avoid bad ones).

The way it would work is:
1. You make a checklist and tick boxes to make the configuration you want the list to return to each day.
2. Click the option "Save repeating configuration", which prompts you to select a time of the day (and/or week/month/year) to reset the list to this state.
3. Done. The list will reset to this state at the specified time and interval.

**Comment by tibbi** [comment]
that isnt on the roadmap, dont expect having it
