### ISSUE TITLE
Move the FAB to the menu

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Notes#52]
- Adding a new note is not as common of an action (for me) as editing an existing note
  - Having additional screen space at the bottom of the note would be as valuable as the fab.
- Because the FAB is hidden when editing a note, it can be difficult to find.
  - I've had a couple experiences where I'm writing something, want to create a new note, look in the menu, and for a moment am confused. "Where's the option to create a new note?" Then I remember I have to hide the keyboard first.
This is pretty much the opposite of what a fab should be.

I think [this article](https://medium.com/tech-in-asia/material-design-why-the-floating-action-button-is-bad-ux-design-acd5b32c5ef#.isatm06zq) applies in this situation.

**Comment by mueller-ma** [comment]
I find it really annoing to close the keyboard manually to create a new note. I think it would be the best to move it next to the "rename a note" button

**Comment by smichel17** [comment]
@tibbi if you agree that we should do this, I can probably make a MR to do it.

**Comment by tibbi** [comment]
yea you can do it, make the "New note" (needs new string) the 2nd menu item after Open note, i guess Rename is not used often anyway. Remove the coordinatorlayout of main activity too. 
compile 'com.android.support:design:25.0.1'  might be not needed anymore either, check it out.
