### ISSUE TITLE
Crash if œ char is present in an existing entry

### ISSUE THREAD

**Issue by pmpk1n** [SimpleMobileTools/Simple-Notes#520]
I am encountering a crash of the app.

Steps to reproduce in a LIST note :

1. Add an entry with the 'œ' char, for example (the french word for eggs) : œufs
2. The entry is correctly added to the list
3. Quit the application manually
4. Start the application
5. Add another entry to the list
6. The application stop and doesn't add the new entry

And it becomes impossible to add another entry to this list.

7. Remove the 'œufs' word from the list
8. Quit the application manually
9. Restart the application
10. And now you can add new entries to the list again

Version 6.11.0 Pro from F-droid.

**Comment by KrasnayaPloshchad** [comment]
I believe this would be painful experience for French speaking users.

**Comment by 16arpi** [comment]
I tried to re-create the bug again but it went fine. Is it still there for some users or can we say that the bug is fixed ??

**Comment by pmpk1n** [comment]
It works for me.
Thank you.

You can close the ticket imo.
