### ISSUE TITLE
[Feature] Block keyboard if not needed

### ISSUE THREAD

**Issue by thatwasso** [SimpleMobileTools/Simple-Notes#523]
When I scroll notes I always have trouble with the keyboard popping up even if not needed.

Adding an option to block keyboard (and unlock if necessary) so you aren't annoyed anymore by keyboard popping up, worst in small screens.

A read-only option (so keyboard doesn't pop up) could be also a great addition

**Comment by tibbi** [comment]
Hi, just avoid clicking on the note, it wont show up

**Comment by thatwasso** [comment]
> Hi, just avoid clicking on the note, it wont show up

Am I reading this for real?

**Comment by FOSS-Love** [comment]
I would love to avoid clicking, but the problem rises when i want to copy some text from notes, i dont want to edit still it enters into edit mode.

A floating action button toggling between edit, and view only would be a great addition.
