### ISSUE TITLE
Note contents erased

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Notes#527]
The contents of two note files were unexpectedly erased today.  
I usually have a couple of notes (eg. to do list) open for quick access with autosave turned on.
The associated text files are also blank with a 0 kb data size, and an access time when I wasn't using my phone.
There was no unusual phone usage today, no updates or installs.

I hope that there's a cache of the un-erased notes on my phone somewhere?  I don't have root access.
Thanks for your help

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by slugboy6000** [comment]
I'm using Simple Notes from FDroid and the latest Lineage OS build.
Sorry for the delayed response, I have limited connectivity.
________________________________

**Comment by tibbi** [comment]
hard to say what happened in these cases though, I can just keep an eye on it. Maybe if you find a way of reproducing it, it will help
