### ISSUE TITLE
Nextcloud Support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [SimpleMobileTools/Simple-Notes#530]
Being able to sync notes with a Nextcloud server would be a great addition to the app. It would let multiple phones sync up the notes, provide an automatic backup, and let you access your notes on another device connected to your Nextcloud server. Would this be considered? Thank you.

**Comment by tibbi** [comment]
our apps have no internet access, dont expect having that
