### ISSUE TITLE
Not enough space for text

### ISSUE THREAD

**Issue by Npa972** [SimpleMobileTools/Simple-Notes#540]
Hi,
In french chronometre is to long and do not enter on one line
Thank's for all these great app !
![image](https://user-images.githubusercontent.com/49346431/175832638-cedc97ec-2f44-4215-833c-3e2fa8205c84.png)

**Comment by Npa972** [comment]
Oh sorry i just realize that i wrote in simple-notes but of course it is a bug in simple-clock...

**Comment by tibbi** [comment]
right, didnt notice. Im working on it already, but you can move it if you want.
