### ISSUE TITLE
Switch checklist's default file-extension from .txt to .json

### ISSUE THREAD

**Issue by Jonta** [SimpleMobileTools/Simple-Notes#559]
Repro:

- Make new checklist
- Add some items to it
- Triple dot
- Export as file

Happens:

- Default file-extension is `.txt`

Expected:

- Default file-extension is `.json`

Slightly related: https://github.com/SimpleMobileTools/Simple-Notes/issues/533

**Comment by tibbi** [comment]
the problem with json is the application/json mimetype, so it is difficult to open it with some text editors

**Comment by Jonta** [comment]
- Shame
- `jq` doesn't autocomplete for me on a `.txt`-file
- Hence this issue
- Are we talking about a lot of text editors?
- If not: Which ones?

:)
