### ISSUE TITLE
Share to new note

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Notes#56]
It would be great if, when sharing text from another app, I could share to a new note.

**Comment by gsantner** [comment]
Even better, if the user had the choice, to create a new note, or to append (`"\n"+Text`) to a note.

**Comment by trubitsyn** [comment]
@tibbi this can be closed :)

**Comment by trubitsyn** [comment]
Hmm, I'm not sure. Should I implement appending text to existing note as @gsantner suggested?

**Comment by tibbi** [comment]
ye after sharing you can first display a dialog with 2 radiobuttons "Append to an existing note" and "Share into a new note" or so, use the generic RadioGroupDialog for it. Check the settings how its used. For appending into an existing note use the OpenNoteDialog.

**Comment by gsantner** [comment]
my 2c: Maybe show a list with bigger option "New note" on top, and below that all other notes (which can be appended to)

**Comment by tibbi** [comment]
true, combining it to 1 dialog would probably be even better

**Comment by trubitsyn** [comment]
Yes, I've been testing it for a while and it takes too many clicks with two dialogs.
