### ISSUE TITLE
A problem with importing a checklist

### ISSUE THREAD

**Issue by WX4300** [SimpleMobileTools/Simple-Notes#568]
1. I imported a checklist (I previously saved it on my device)
2. I clicked "Open file" and selected my file with the checklist
3. The file was imported to the app but all of my tasks were imported into one task (3 tasks added one after another in such a form - yes, I imported it as a checklist):
[{"dateCreated":0,"id":0,"isDone":false,"title":"Check something"}]

**Comment by tibbi** [comment]
yeah, some export/import related changes will surely be added, it go quite confusing over time.
