### ISSUE TITLE
Feature Request: Auto import from exported files?

### ISSUE THREAD

**Issue by betsythefc** [SimpleMobileTools/Simple-Notes#569]
I see you can export a file, and it keeps the contents of the exported files updated when changes are made in the app. I would like it to also go the other way.

I use Syncthing to sync text notes between my devices, and would like changes made on my computer to be reflected in the app.

**Comment by tibbi** [comment]
thats how it works already if you have a note synced with a file. Whatever changes, it changes the other thing too.

**Comment by betsythefc** [comment]
Ah, when I tested this, only changes made in Simple Notes were reflected, but when I changed the text file elsewhere, it didn't update in Simple Notes, though I'll test it again

**Comment by betsythefc** [comment]
I just tested and it works. Sorry for the erroneous feature request!
