### ISSUE TITLE
Opening notes via File Manager

### ISSUE THREAD

**Issue by cenktaskin** [SimpleMobileTools/Simple-Notes#581]
Hey @tibbi,

I just started using this app. I have some local notes that I have synchronization in place. App serves my purpose quite well when I open these via "Open file" in the app. It offers me two options (shortly) "in-place", "deep-copy". I can choose "in-place" and my use-case is resolved. 

I was looking around how to make this workflow simpler. Rather have access to my notes directory easily. Two ways to achieve this:
1) Expecting notes app to be aware of the dir structure of a root notes app. As [described](https://github.com/SimpleMobileTools/Simple-Notes/issues/9#issuecomment-246592270) by another user on #324.
2) Have file manager to open the notes.

In my opinion, 2) is a much better way to solve this since its file manager's duty to mess with the directory structure. And there is no point to re-invent wheel for each app.

My question/problem is when I open the note via Simple File Manager, it opens the file in the aforementioned "deep-copy" mode. Is there any way this behaviour to default to "in-place" somehow?

Thanks for the work!

**Comment by tibbi** [comment]
the app has no storage access, it cannot scan folders

**Comment by cenktaskin** [comment]
Scan folders?


> My question/problem is when I open the note via Simple File Manager, it opens the file in the aforementioned "deep-copy" mode. Is there any way this behaviour to default to "in-place" somehow?

I can already "Open file" in the app. I'm simply asking how to make that behaviour occur when I click on the note via file manager.

Did you _try_ to mean that this issue belongs to the file manager repo?

**Comment by tibbi** [comment]
no, I misunderstood it. Anyway, it opens the by importing the content only, doesnt update the file itself. I want to rethink the whole importing part, it got quite messed up over time.

**Comment by cenktaskin** [comment]
[This is the way](https://github.com/SimpleMobileTools/Simple-Notes/issues/324#issuecomment-583423738) you advised it to be used, and it makes sense. Is there any issue to follow this?

**Comment by tibbi** [comment]
not really, it cannot be followed
