### ISSUE TITLE
Renaming Or Editing Item(s)

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-Notes#582]
Maybe I am not seeing where it is to rename a checklist item? All I see is a plus sign below and the trash can and other stuff but no way to rename checklist items. Yes I can rename the whole note but not rename a specifkc item in the checklist? Any ideas?

**Comment by tibbi** [comment]
select it by long pressing and use the Rename top menu item.

**Comment by HonestAbe7** [comment]
Ok. Thanks. Just found it.
