### ISSUE TITLE
Request : Setting to add items to top of checklists

### ISSUE THREAD

**Issue by xcelente** [SimpleMobileTools/Simple-Notes#583]
New items are automatically added to the bottom of lists. I never want them there! :) I find myself constantly adding to the end and then manually moving them all the way to the top / near the top. Perhaps not everyone wants this so maybe you can put it in Settings? "Add items to the top"

Thanks

**Comment by Aga-C** [comment]
@tibbi This was already implemented. Why it was removed?

**Comment by tibbi** [comment]
I had that feeling too, not sure

**Comment by tibbi** [comment]
right, it was colliding with custom sorting, will take a look at it
