### ISSUE TITLE
too much spacing between items on the checklist widget

### ISSUE THREAD

**Issue by github-cygwin** [SimpleMobileTools/Simple-Notes#593]
Hi,

I purchased the notes app lately, and I'm mostly happy with it.

I'm using the checklist widget as simple shopping list.  The only problem I have with it is, that the spacing between the items on the checklist widget is too wide.  It takes so much space, that only few items are visible at a time.

It would be great if the spacing between the items could be managed by the user, or generally be made tighter.

Thanks,
Corinna

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Notes/issues/267.

**Comment by github-cygwin** [comment]
oh, right, I scanned the open issues but missed this one.

Closing as duplicate.

**Comment by github-cygwin** [comment]
oh, right, I scanned the open issues but missed this one.

Closing as duplicate.
