### ISSUE TITLE
[Feature Request] Add "Create shortcut" option

### ISSUE THREAD

**Issue by dvmc** [SimpleMobileTools/Simple-Notes#598]
It would be great to have a "Create shortcut" option, so that you can place a shortcut to a specific note on your home screen, which gets you directly to the editable note. This is very similar to the "Create shortcut" option that you have in Simple File Manager.

Right now, you could export the note and then create a shortcut with Simple File Manager, which would add more extra steps if you want to modify that file. Or you could use a widget, but that does not let you put the note into a home screen folder.

**Comment by tibbi** [comment]
you can already use widgets for that

**Comment by dvmc** [comment]
This is not the same. For example, one thing that you can do with shortcuts and you can not do with widgets is putting it inside a folder on the home screen (see the first post).
