### ISSUE TITLE
Theme selection in a extra window

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Notes#60]
Allmost every other app uses a popup window with a list of themes to select (even when there are only two). I don't know if this or that is material design guidline, but it would be nice, when you can change that. Because it is used in every of your app, maybe you can include this in SimpleCommons

**Comment by tibbi** [comment]
The "dark theme" toggle in Settings is the oldschool way of setting the theme, there is already a lot more advanced color customization included in Commons library, which is for now available only in the gallery and calendar. It will come to other apps too someday.

**Comment by tibbi** [comment]
color customization has been added already
