### ISSUE TITLE
{Feature Request} passcode for webapp 

### ISSUE THREAD

**Issue by tanujrarh26** [SimpleMobileTools/Simple-Notes#605]
**passcode** for android is very good feature
i was wondering if **passcode** can also be available in **web app** it would really be great
**thanks in advance**

**Comment by tibbi** [comment]
no idea what you mean here, but it sounds way too advanced

**Comment by tanujrarh26** [comment]
> no idea what you mean here, but it sounds way too advanced

I mean just like how we have option to lock the simple note app with a passcode (using in app lock ). Just like the android app can we have the same passcode lock capability in web app (in browser )
🙂

**Comment by tibbi** [comment]
I dont know what web app you mean, our apps are offline

**Comment by tanujrarh26** [comment]
> I dont know what web app you mean, our apps are offline

Sorry bro my bad it was another app that has same name sorry 😅
