### ISSUE TITLE
Import Folder - menu option missing

### ISSUE THREAD

**Issue by hansaplasst** [SimpleMobileTools/Simple-Notes#610]
Hi There,

The `Import folder` menu option is missing in GrapheneOS.

Left is LineageOS on android 8. Right is GrapheneOS on android 13
![image](https://user-images.githubusercontent.com/27355296/229894525-bf588278-d55b-47b1-98e8-6450770fd16f.png)

Also. The menu options `Open file` and `Import notes` (on the right) is ambiguous.

Both phones have Simple-Notes v6.15.4 installed

**Comment by Aga-C** [comment]
It's missing due to newer Android restrictions. It's related to https://github.com/SimpleMobileTools/Simple-Notes/issues/592.
