### ISSUE TITLE
Files that get synced to the phone through syncthing cannot be opened by Simple Notes

### ISSUE THREAD

**Issue by Switch123456789** [SimpleMobileTools/Simple-Notes#614]
Whenever I change a file on my Desktop-PC and syncthing syncs it to my phone, Simple Notes shows an error and removes the note from the app.

The error is something like: `permission denial: writing .....` (it disappears pretty fast)

I store the files in `/Android/media/com.simplemobiletools.notes.pro/Notes/`

Maybe syncthing changes the ID of the file and therefore the permission for Simple Notes get changed? But I was under the impression that Simple Notes should have full access to it's own app-directory anyway. So this shouldn't matter but I don't know for sure.

Filesystem (PC): ext4
Phone: Fairphone 3
Android: 13 (iodé 4.1)
App: 6.15.4 Pro

**Comment by tibbi** [comment]
sadly file management on Android is a lot more difficult, we dont have access to such files

**Comment by Switch123456789** [comment]
What do you mean by "such files"?

Simple Notes DOES have access. Even if I manually change the file with another app, Simple Notes has access afterwards. It ONLY craps itself after I updated the file using syncthing. I can even manually add it back to Simple Notes afterwards and it still has access.

If it is caused by a changed file-ID, it can be easily fixed by allowing access to the folder through Androids SAF. Or add the flag that allows Android to grant SN access to all files on the phone.

**Comment by Switch123456789** [comment]
Can you help me understand? Again SN has access to those file, I can send you video-proof or whatever if you just can't believe me. I use SN every day for many years now, it works!!!

About accessing folders: Syncthing does it this way, KDE Connect does it, almost every camera app I ever used since the introduction of SAF does it this way. Why exactly is it that SN can't access all files within a specified folder through SAF if many other apps can?

In the Android Documentation it says [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE)
"Apps can **fully manage** documents within the returned directory".

For full access there is [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files#all-files-access)
An app can request **all-files access** from the user by doing the following: Declare the [MANAGE_EXTERNAL_STORAGE] permission in the manifest.

So it says in the documentation it is possible, I use apps every day that does it. So what exactly am I missing here that prevents SN from doing it? Please educate me, I am so confused at this point.

**Comment by tibbi** [comment]
file manangement on Android is really difficult and it keeps getting more messy with every new OS version. Anyway, honestly this issue is way too specific for your usecase to really work on it now.

**Comment by Switch123456789** [comment]
I wonder why [this request](https://github.com/SimpleMobileTools/Simple-Notes/issues/335) is still open if using syncthing is "way too specific". But fine, since I need to sync my notes, I'll try another app.

**Comment by adapt-L** [comment]
it seems to work fine now but the widget won't update unless it is redrawn
