### ISSUE TITLE
Import Bug

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Notes#616]
I tried to import a once exported note into Simple-Notes and got the following error:

Error: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: notes.value (code 1299 SQLTIE_CONSTRAINT_NOTNULL)

**Comment by nopeppermint** [comment]
Version 6.15.4 Pro
Android 11, LineaseOS 18.1
Samsung Galaxy A5 SM-A520F

**Comment by tibbi** [comment]
what app have you exported the note from?

**Comment by nopeppermint** [comment]
the same app, but it was on the 30.06.22, broke my phone wanted to go back to this old backup

**Comment by tibbi** [comment]
hard to say what went wrong there, just open the note with any text editor and copypaste its content

**Comment by nopeppermint** [comment]
the strange thing is, I am able to import text notes from then but checkbox notes seems to fail all

**Comment by nopeppermint** [comment]
and if I open it in the file explor and select there the simple notes app, it works as well for checkboxes, only the import functionality in the app doesn't work

**Comment by nopeppermint** [comment]
I think the missing thing is the checkbox to determind if it's a textnote or a checkbox note, because this checkbox only pop's op when I open the note file from the explorer but not in the importer!

**Comment by nopeppermint** [comment]
or add a dedicated checkbox import and "proper" identification of checkbox or text note import ;-)

**Comment by tibbi** [comment]
maybe the structure was different back then, the app isnt really optimized to recognize and properly handle all past note structures
