### ISSUE TITLE
Opening file from Nextcloud sync causes NetworkOnMainThreadException

### ISSUE THREAD

**Issue by peterDSM** [SimpleMobileTools/Simple-Notes#619]
Hey. Thank you for the great set of apps. I love them and use nearly all of them.

As a user I want to be able to share a note (check list in my case) via Nextcloud with other family members. To achieve this I copy the list file to nextcloud sync folder. When opening the file from nextcloud folder I get a NetworkOnMainThreadException.

Not sure if this same issue also occurs for Dropbox and other sharing services or if this is Nextcloud specific behavior.

Steps to reproduce (App Version 6.15.4 Pro from FDroid, Android 13)
1. Create new checklist in notes app
2. Export checklist as file to nextlcoud share folder
3. Remove checklist from notes app  without deleting the file
4. In notes app click "Open file" and select file in nexcloud share folder

This results in an NetworkOnMainThreadException.

Observation: The same file can be opened with Simple FileManager.

#38 and #354 mention synchronizing on a file basis as a solution for cloud integration. However, in my case seems not to be working

**Comment by tibbi** [comment]
a proper error should be shown in 6.15.6

**Comment by peterDSM** [comment]
I am not sure if I did not express clear enough what I am doing or if that is missing knowledge about the system on my side. 
I was talking about access to Android/media/com.nextcloud.client/nextcloud/[accountname] folder. 
I am not sure if internet permission is really required to access that. If I understand it correctly from permissions Simple File Manager also does not have internet access, correct? Because access from that app is working.

Excuse me if I am totally wrong here. I really don't know much about the android ecosystem.

**Comment by tibbi** [comment]
well, the exception was thrown by the system, not us. So the app is definitely trying to access the internet somehow.

**Comment by peterDSM** [comment]
Ok. Thank you very much for the clarification and sorry for the inconvenience.
