### ISSUE TITLE
Third party notes can be doubled

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Notes#62]
reproduce: I go to "about" and than "third party licenses", click one link and than use the "back" button of my phone

Actuall: every license is doubled and the links are in font color, not primary color

Expected: looks like before clicking on a link

**Comment by smichel17** [comment]
I can't replicate this.

**Comment by mueller-ma** [comment]
Some additonal info:
Notes v2.0.1 fdroid
Android 6.0.1
Open links with forkhub 
custom colors

and

Notes v2.0.1 fdroid
Android 5.1.1
Open links with firefox
default colors

I could not reproduce it with v1.24. This might be a bug in Simple Commons

@smichel17 What version do you use?

**Comment by tibbi** [comment]
ye its an issue with Simple Commons, should be easy to fix

**Comment by smichel17** [comment]
Noted v2.0.1
Android 5.0.1
Samsung galaxy s4
Firefox
Default colors

**Comment by tibbi** [comment]
it should be fxed in the gallery, I wont publish a new version of the remaining apps just for that. I will publish them sooner or later.

**Comment by mueller-ma** [comment]
@tibbi I will test it when the new version is availabe on fdroid
