### ISSUE TITLE
[fr] implement a "Read Only" option.

### ISSUE THREAD

**Issue by nameless326** [SimpleMobileTools/Simple-Notes#635]
each individual note should have a "Read Only" option, so we won't be able to edit them by accident while we're reading/scrolling them.

that's literally what happens to me, lol.

I accidentally press certain keys when I'm trying to scroll down the notes to read them.

**Comment by tibbi** [comment]
that isnt really on the roadmap now

**Comment by nameless326** [comment]
@tibbi this feels more like a bug, than a feature request.

I edit notes by accident all the time when I'm trying to scroll ro read them.

an option to have a note as "Read Only" could fix that... or, an option to permanently disable the keyboard on a note.

**Comment by tibbi** [comment]
how could you edit anything by scrolling...

**Comment by nameless326** [comment]
because the keyboard keeps showing up randomly...

a simple option to disable the keyboard (or, a read only mode) would fix this issue.
