### ISSUE TITLE
[Feature Request] List View Menu

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Notes#637]
Requesting an option to start the app to show up as a list view where you can see a list of all the notepads created, you select it and then it opens that notepad.
Instead of needing to swipe left and right between notepads just to find the one you want.

**Comment by Aga-C** [comment]
Check: Settings ⇾ Show a note picker on startup.

**Comment by seniorm0ment** [comment]
Yes, however that only functions on startup.
When I am in a note, you cannot hit the back button to reshow that menu. You would have to exit the app the  reopen it to get that menu to show. Otherwise you are back to swiping.

**Comment by Aga-C** [comment]
You can use this button:

![image](https://github.com/SimpleMobileTools/Simple-Notes/assets/85929121/c98488b7-43a2-4775-82a3-a2cce79bf114)

**Comment by seniorm0ment** [comment]
Ah. Ok it would be nice to be able to sort them so beyond that I see.
I will close this ticket thanks.
