### ISSUE TITLE
Primary color is visible for a short time when opening notes via widget

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Notes#64]
It seems that the app loads slower when opening via widget so you will see the default primary color.

Maybe connected to https://github.com/SimpleMobileTools/Simple-Commons/issues/20

**Comment by tibbi** [comment]
well ye, it cannot be changed during runtime

**Comment by mueller-ma** [comment]
@tibbi What about different behavoir when starting through app or widget?

**Comment by tibbi** [comment]
hm ill reopen it then to check how can it be tweaked in the future, wont experiment now

**Comment by mueller-ma** [comment]
@tibbi Can you fix this also in Calender?

**Comment by tibbi** [comment]
ye sure, i can add it to calendar and music player too
