### ISSUE TITLE
Serious bug: "Export all notes" deletes all notes except current one

### ISSUE THREAD

**Issue by pierstitus** [SimpleMobileTools/Simple-Notes#647]
I wanted to backup my notes, but noticed all exported files were empty except the selected note. Also the text inside the other notes was gone afterwards.
If you switch back and forth to the other notes before exporting it seems to work well, but if you exit the app (close it in app switcher) and start it again they are lost again. So it seems the notes are not loaded into memory or so.

I used version 6.15.4 from fdroid on Android 8.0.0
I've updated to 6.15.5 and haven't reproduced the bug yet, but since it's such a serious issue I'm already posting it, if you want I can look further into it.

Thanks for the great tools btw!

**Comment by tibbi** [comment]
nobody really reported anything like that, I cannot reproduce it either. Hard to say what was wrong there, but reopen the issue if it happens again.
