### ISSUE TITLE
Have a view of "last used notes"

### ISSUE THREAD

**Issue by ezzra** [SimpleMobileTools/Simple-Notes#664]
_I might be a heavy user of the app, currently I have around 100 notes and its getting quite complicated to switch between them and makes kind of tedious working with the app._

I have but only around 5-10 notes I use frequently every day. It would be very comfortable to have a view, which shows only my last used notes, maybe even with the posssiblity set up as a startpage when opening the app.

**Comment by tibbi** [comment]
that isnt on the roadmap, the app isnt supposed to be used with 100 notes

**Comment by ezzra** [comment]
> the app isnt supposed to be used with 100 notes

really, you want to make this a limit? So its just for playing for a little use, that is not how I understand "simple" :-/
