### ISSUE TITLE
organise notes in groups

### ISSUE THREAD

**Issue by ezzra** [SimpleMobileTools/Simple-Notes#665]
_I might be a heavy user of the app, currently I have around 100 notes and its getting quite complicated to switch between them and makes kind of tedious working with the app._

Here I propose a feature, to organise notes in groups or folders. I understand that a counter-argument would be to keep the app simple and I can see that. I would therefore suggest that groups are only displayed if at least two exist.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Notes/issues/158.

**Comment by ezzra** [comment]
thanks
