### ISSUE TITLE
[Feature Request] Changes to how notes are selected/opened 

### ISSUE THREAD

**Issue by K4LCIFER** [SimpleMobileTools/Simple-Notes#667]
It currently feels somewhat clunky, and overcomplicated to have files in the "tab" format where you swipe left or right between them. I think it would be much simpler to just have a list that displays all the note files, and you simply select from that list to open a note. In addition to this, I would recommend removing the note grid/open note dialogue (opened by tapping on the folder icon); it is rather unintuitive, and overcomplicated. It would be better handled by the afformentioned list.

**Comment by tibbi** [comment]
we dont plan changing it now
