### ISSUE TITLE
Checklists merged to one entry with meta data after update to to 6.16.2

### ISSUE THREAD

**Issue by CodeIsDoc** [SimpleMobileTools/Simple-Notes#672]
- **OS**: Android 13
- **SimpleMobileTools Simple-Notes version**: 6.16.3
- **Reproducability:** Unknown.
- **Workaround:** Manual editing.

Upon upgrading from 6.16.1 to 6.16.2, all checklists were reduced to one entry containg the all previous entries along with the meta data.

An example of the checklist "boardgames" after upgrading:

`[{"dateCreated":0,"id":0,"isDone":false,"title":"[{\"dateCreated\":0,\"id\":0,\"isDone\":false,\"title\":\"[{\\\"dateCreated\\\":0,\\\"id\\\":0,\\\"isDone\\\":false,\\\"title\\\":\\\"[{\\\\\\\"dateCreated\\\\\\\":0,\\\\\\\"id\\\\\\\":0,\\\\\\\"isDone\\\\\\\":false,\\\\\\\"title\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"dateCreated\\\\\\\\\\\\\\\":1690973020210,\\\\\\\\\\\\\\\"id\\\\\\\\\\\\\\\":1,\\\\\\\\\\\\\\\"isDone\\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Seventh continent\\\\\\\\\\\\\\\"},{\\\\\\\\\\\\\\\"dateCreated\\\\\\\\\\\\\\\":1690973020210,\\\\\\\\\\\\\\\"id\\\\\\\\\\\\\\\":2,\\\\\\\\\\\\\\\"isDone\\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Eclipse\\\\\\\\\\\\\\\"},{\\\\\\\\\\\\\\\"dateCreated\\\\\\\\\\\\\\\":1690973020210,\\\\\\\\\\\\\\\"id\\\\\\\\\\\\\\\":3,\\\\\\\\\\\\\\\"isDone\\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Zombicide\\\\\\\\\\\\\\\"},{\\\\\\\\\\\\\\\"dateCreated\\\\\\\\\\\\\\\":1690973020210,\\\\\\\\\\\\\\\"id\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"isDone\\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Scythe\\\\\\\\\\\\\\\"}]\\\\\\\"}]\\\"}]\"}]"}]`

Upgrading to 6.16.3 did not solve the issue.

**Comment by CodeIsDoc** [comment]
I dont think so, at least not intentionally. The checklist was created manually from scratch. The note was never exported.

I can not find any files on the system it could correspond to.

**Comment by tibbi** [comment]
maybe it was some glitch at wrong updates, but it shouldnt happen anymore. Sorry for that
