### ISSUE TITLE
suggestion: Option to use old Open Note dialog

### ISSUE THREAD

**Issue by Cre3per** [SimpleMobileTools/Simple-Notes#673]
I have ~25 notes.   
The new Open Note dialog makes notes difficult to find, because there's a lot of scrolling involved and individual notes differ in length.  
The new dialog also shows note contents, which can be a privacy concern when switching notes in public.

I'd like to use the old dialog again. Either as an option or by undoing the relevant changes of 6.16.0 or 6.16.2 (not sure which version changed from a list to cards)

**Comment by tibbi** [comment]
it isnt on the roadmap
