### ISSUE TITLE
Themes other than Black & White should have access to Accent color

### ISSUE THREAD

**Issue by SkyDontFall** [SimpleMobileTools/Simple-Notes#681]
I noticed that the black and white theme has an extra section called "Accent color of Black & White theme". (Check Image: https://cdn.discordapp.com/attachments/728207504881745983/1146600795589058570/Screenshot_2023-08-31-05-47-46-967_com.simplemobiletools.notes.pro.jpg)

This option should be available for any theme and shouldn't be restricted to the black and white theme. Because if I change even one of these variables: Text color, Background color or Primary color; the option disappears.

Here I changed the text colour to be a little darker: ![Text Colour Changed](https://cdn.discordapp.com/attachments/728207504881745983/1146600795870068816/Screenshot_2023-08-31-05-48-04-183_com.simplemobiletools.notes.pro.jpg)
Here I changed the primary colour to a dark grey: 
![Primary Colour Changed](https://cdn.discordapp.com/attachments/728207504881745983/1146602010238537758/Screenshot_2023-08-31-05-57-05-272_com.simplemobiletools.notes.pro.jpg)

In both situations the "Accent color of Black & White theme" option disappears.
Slightly darker Text Colour:
![Darker Text Colour](https://cdn.discordapp.com/attachments/728207504881745983/1146600796134330420/Screenshot_2023-08-31-05-48-06-850_com.simplemobiletools.notes.pro.jpg)

Slight lighter Primary Colour:
![Slight lighter Primary Colour](https://cdn.discordapp.com/attachments/728207504881745983/1146603257792299088/Screenshot_2023-08-31-06-02-02-188_com.simplemobiletools.notes.pro.jpg)

Both make the text of titles unreadable and the checkmarks disappear if I only modify the text colour.
Black & White Theme:
![B&W](https://cdn.discordapp.com/attachments/728207504881745983/1146607033563496489/Screenshot_2023-08-31-06-16-47-976_com.simplemobiletools.notes.pro.jpg)

Slightly darker Text Colour:
![Slightly darker Text Colour](https://cdn.discordapp.com/attachments/728207504881745983/1146605110038892624/Screenshot_2023-08-31-06-08-32-348_com.simplemobiletools.notes.pro.jpg)

Slight lighter Primary Colour:
![Slight lighter Primary Colour](https://cdn.discordapp.com/attachments/728207504881745983/1146605110353469472/Screenshot_2023-08-31-06-08-48-946_com.simplemobiletools.notes.pro.jpg)

**Comment by SkyDontFall** [comment]
I just realized that the accent colour just overwrites the Primary colour. Then what's the point of having this option?  Why not just call it a Black (OLED) theme and have the primary colour set to Orange.

Or have the primary colour dictate the colour of the top bar and the accent colour dictate everything else.

Like this: ![Colours](https://media.discordapp.net/attachments/728207504881745983/1146610534456754318/Screenshot_2023-08-31-06-21-57-765_com.simplemobiletools.notes.pro-edit.jpg)

![Colours 2](https://media.discordapp.net/attachments/728207504881745983/1146609299859185735/Screenshot_2023-08-31-06-25-08-712_com.simplemobiletools.notes.pro-edit.jpg)

**Comment by SkyDontFall** [comment]
Didn't mean to close it. Sorry

**Comment by tibbi** [comment]
other themes use the primary color instead of accent
