### ISSUE TITLE
[Feature Request] button to delete all the text in the note

### ISSUE THREAD

**Issue by peimando** [SimpleMobileTools/Simple-Notes#691]
Hi, It would be ideal to have a button to delete all the text written in the note. I use the app to communicate with deaf people through the translator. I type my messages in the note-taking app, but every time I want to delete the text to continue the conversation, I have to select everything and delete it. It becomes complex in long conversations.
![noteapp](https://github.com/SimpleMobileTools/Simple-Notes/assets/101684906/6f46eacb-8761-4987-a769-1b65de20e1d6)

With thanks in anticipation

**Comment by tibbi** [comment]
you can already delete text by the casual system way
