### ISSUE TITLE
Why arent on Note picker page cancel and add note buttons on left and right side?

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Notes#699]
There two buttons on right side and nothing on left side.

![IMG_20231023_213356.jpg](https://github.com/SimpleMobileTools/Simple-Notes/assets/75314629/876deaa8-3cef-4663-9950-0e32225c0866)

**Comment by inson1** [comment]
@tibbi 
Everything is on one side of the window and on other side there is nothing

**Comment by tibbi** [comment]
of course, it is easier to reach with your finger

**Comment by inson1** [comment]
@tibbi Yes, but why then is anything on left side? Why arent all buttons on right side?
The app appearance also matters.
