### ISSUE TITLE
[Feature Request] Reminder for notes 

### ISSUE THREAD

**Issue by BreakfastSerial** [SimpleMobileTools/Simple-Notes#707]
I'm missing a feature to set a date/time reminder for notes.

![material-date-time-picker-768x432](https://github.com/SimpleMobileTools/Simple-Notes/assets/29393958/ff95b64e-29d9-4e5f-be39-f976faf37a9d)

**Comment by tibbi** [comment]
that isnt on the roadmap, just use a calendar for it
