### ISSUE TITLE
feature request? choose folder for text files

### ISSUE THREAD

**Issue by rogue-ronin** [SimpleMobileTools/Simple-Notes#714]
I'd like to sync these presumably plain-text files with SyncThing so I can write them on a computer and have them appear in the notes app - I'm thinking of the similar XFCE notes app that just saves text files to a folder.

Is this possible already? IE: is the save folder accessible to the user? If not, could we choose the folder that the notes are saved in?

Or am I missing something obvious? :)

**Comment by like-a-glitch** [comment]
That's exactly what I use syncthing and simple-notes for.

I got it working like this:
- pc
    - create a folder and sync it with syncthing
    - create a txt in this folder
- phone
    - simple-notes > three dot menu > open file
    - select the txt file created on pc
    - select "update the file itself at updating the note"

**Comment by Maxitendo1** [comment]
@like-a-glitch @rogue-ronin SimpleMobileTools apps were sold to ad and spyware company. Fork is here:

https://github.com/FossifyOrg

**Comment by rogue-ronin** [comment]
Thanks for the heads-up. May they reap the whirlwind.
