### ISSUE TITLE
Cursor does not initially appear in blank notes

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Notes#76]
Steps to reproduce:

- Create a new note

Expected behavior: there is a blinking cursor
Actual behavior: No cursor is shown, although the keyboard is open and typing works.

Typing any letter causes the cursor to be shown, even if you then erase that letter.

**Comment by trubitsyn** [comment]
@tibbi I am unable to reproduce that. There _is_ a blinking cursor when a default note is shown and after new note creation. It's very thin, though.

Using version 2.2.0 on Android 6.0

**Comment by mueller-ma** [comment]
I can reproduce it

**Comment by smichel17** [comment]
I still experience it on 2.2.0, android 6.0.1.

**Comment by trubitsyn** [comment]
@mueller-ma @smichel17 could you please try to reproduce it by compiling https://github.com/trubitsyn/Simple-Notes? I tried to make a fix for that.

**Comment by tibbi** [comment]
that line in the pull request is there so that the cursor changes it color appropriately. I could reproduce this issue by creating a note that after the "General note", ideally on the position 3+. The main issue was an invisible keyboard in my case, not a cursor.

**Comment by trubitsyn** [comment]
Oh, now I got that! My bad.

**Comment by smichel17** [comment]
>Oh, now I got that! It wasn't told in the issue how many notes should have been created though.

I didn't realize that the number of notes had anything to do with it. Probably should have included the info on a hunch, though. I currently have 5 notes. I should be able to test the latest soon.

**Comment by tibbi** [comment]
Im often not told how to exactly reproduce issues, which is pretty obvious. Users just dont know what causes them, you have to experiment.

**Comment by trubitsyn** [comment]
Yes, I should have tested more thoroughly, anyway.
