### ISSUE TITLE
Application crashes when note title is created or edited if orientation has been changed after changing the title

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#80]
Steps to reproduce:

1. Press + icon
2. Type something in a text field

or

1. Open note title rename dialog
2. Change title

then

3. Make orientation change (e.g. rotate your device)
4. Press OK
5. Application crashes, though a note with the given name shows up then

**Comment by mueller-ma** [comment]
This wiped some of my notes.

**Comment by tibbi** [comment]
Ive added some quick fix so it wont crash, just tell an error if something went wrong at renaming or creating new note. Saving should work fine.
