### ISSUE TITLE
Scroll widget text when swiping

### ISSUE THREAD

**Issue by Adrien-Luxey** [SimpleMobileTools/Simple-Notes#84]
Hi there !

Thanks for a vert nice app; now I have all my little thoughts on my home screen :)

Would that be possible to make the text scrollable directly from the widget, instead of having to open the app to see more than the beginning of the selected note?

Thanks, and keep up the good work!
Adrien

**Comment by tibbi** [comment]
Ill close it as a duplicate of #127 as there is more info
