### ISSUE TITLE
Allow to import multiple notes at once

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#86]
An "Import folder" option would be sufficient.

**Comment by trubitsyn** [comment]
Working on this.

**Comment by tibbi** [comment]
well Import Folder is one solution, but I also want to update the filepicker dialog with some checkboxes option. That would be required in multiple apps.

**Comment by trubitsyn** [comment]
Should I wait for the dialog to appear in Commons or should I create it for you to add to Commons?

**Comment by tibbi** [comment]
you can add the "Import folder" option. I will add the "Import files".
