### ISSUE TITLE
Crashes after removal of imported file

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#88]
Steps to reproduce:
1. Open app
2. Import a file, choose to sync changes
3. Hide app
4. Rename or remove the file
5. Go back to app
6. App crashes, but fortunately restarts
7. Note is removed from the app's storage even when the file was renamed, but not removed

Should I file a bug on (7) or it is supposed not to trace filename changes by design?

Thanks

**Comment by tibbi** [comment]
it shouldnt trace filename changes, theres no way I can do that
