### ISSUE TITLE
Allow saving note to a file

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#9]

**Comment by halfwit** [comment]
I'm also interested in something that uses just an underlying directory structure - text files, and opens them. (Secretly, it's so I can reuse my very simple Linux scripts to keep notes, distributing them with syncthing) - I'll be happy to help out on this if I can. Haven't done Android in a while, though.

**Comment by tibbi** [comment]
like an "Open" button where you can select text files to open? I can add it once Im done with the file picker at the file manager :p I want to reuse it at more apps.

**Comment by halfwit** [comment]
Not sure why my email didn't go through, but whatever - my thought was have a setting for "notes directory", and with that set, your application opens in a list view of files - select whichever one, "shopping list" "progamming snippets" or whatever else you have in your random notes dir - and then having that simple edit view once the file is selected

**Comment by halfwit** [comment]
(This would also address #3)

**Comment by tibbi** [comment]
okay I see, so it is indeed #3 :D

**Comment by smichel17** [comment]
I don't think you need to let the user pick a folder for the first round. I would imagine this feature as:

There is a folder, `/storage/emulated/0/simplenotes/`. In that folder, there's a bunch of files, where `Filename.txt` corresponds to a note in the app with the name `Filename`.

If you add a new file to that directory externally, a new note appears in the app. If you add a new note in the app, a new file is created. Then you can sync that directory to the cloud with nextCloud, Google drive, etc -- or just open it in different app if you wanted to do that for some reason.

**Comment by smichel17** [comment]
Also, I'm not sure how helpful it is, but there's some gpl kotlin code for dealing with a file over [here](https://github.com/mpcjanssen/simpletask-android/blob/b2915f311a25d8668c01dbb11565d35e34ad1c55/src/cloudless/java/nl/mpcjanssen/simpletask/remote/FileStore.kt)

**Comment by halfwit** [comment]
That's a fine compromise for me!

**Comment by trubitsyn** [comment]
@tibbi seems like you have implemented this feature already :)
