### ISSUE TITLE
Default cursor placement

### ISSUE THREAD

**Issue by mtbu** [SimpleMobileTools/Simple-Notes#97]
The last update makes the cursor go by default to the end of the file, would it be possible to add an option for placing it at the start or end by default? I normally edit the first line, which is at the top of the widget. Great app otherwise though.

**Comment by tibbi** [comment]
hah, it was changed intentionally as some people wanted it, so guess Ill have to add a setting for it

**Comment by trubitsyn** [comment]
See #98

**Comment by tibbi** [comment]
a toggle will be added in the next version, cursor will be at the end of the note by default
